player_data = 
[
{name : "Cam Newton", position : "QB", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
{name : "Aaron Rodgers", position : "QB", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
{name : "Russell Wilson", position : "QB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"}, 
{name : "Drew Brees", position : "QB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
{name : "Matthew Stafford", position : "QB", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"}, 
{name : "Ben Roethlisberger", position : "QB", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
{name : "Tom Brady", position : "QB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
{name : "Matt Ryan", position : "QB", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
{name : "Philip Rivers", position : "QB", team: "San Diego Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
{name : "Eli Manning", position : "QB", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
{name : "Derek Carr", position : "QB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
{name : "Kirk Cousins", position : "QB", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
{name : "Dak Prescott", position : "QB", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"},
{name : "Jameis Winston", position : "QB", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
{name : "Marcus Mariota", position : "QB", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
{name : "Deshaun Watson", position : "QB", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
{name : "Jared Goff", position : "QB", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
{name : "Carson Wentz", position : "QB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
{name : "Alex Smith", position : "QB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
{name : "Blake Bortles", position : "QB", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
{name : "Case Keenum", position : "QB", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
{name : "Baker Mayfield", position : "QB", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
{name : "Andy Dalton", position : "QB", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
{name : "Jimmy Garoppolo", position : "QB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
{name : "Patrick Mahomes", position : "QB", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
{name : "Andrew Luck", position : "QB", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
{name : "David Johnson", position : "RB", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
{name : "Lamar Miller", position : "RB", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
{name : "Todd Gurley", position : "RB", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
{name : "Kareem Hunt", position : "RB", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
{name : "Ezekiel Elliott", position : "RB", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"}, 
{name : "Le'Veon Bell", position : "RB", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
{name : "James Conner", position : "RB", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
{name : "Devonta Freeman", position : "RB", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
{name : "Mark Ingram", position : "RB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
{name : "Alvin Kamara", position : "RB", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"}, 
{name : "LeSean McCoy", position : "RB", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
{name : "Carlos Hyde", position : "RB", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
{name : "Jordan Howard", position : "RB", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
{name : "Melvin Gordon", position : "RB", team: "San Diego Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
{name : "Jay Ajayi", position : "RB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
{name : "Leonard Fournette", position : "RB", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
{name : "Aaron Jones", position : "RB", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
{name : "Isaiah Crowell", position : "RB", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
{name : "Christian McCaffrey", position : "RB", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
{name : "Marshawn Lynch", position : "RB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
{name : "Dalvin Cook", position : "RB", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
{name : "Bilal Powell", position : "RB", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
{name : "Joe Mixon", position : "RB", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
{name : "Sony Michel", position : "RB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
{name : "James White", position : "RB", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
{name : "Kerryon Johnson", position : "RB", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
{name : "Adrian Peterson", position : "RB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
{name : "Frank Gore", position : "RB", team: "Miami Dolphins", logo : "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", alt : "Mia"},
{name : "Doug Martin", position : "RB", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
{name : "Chris Thompson", position : "RB", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
{name : "LeGarrette Blount", position : "RB", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
{name : "Duke Johnson", position : "RB", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
{name : "Wendell Smallwood", position : "RB", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
{name : "Dion Lewis", position : "RB", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
{name : "Alex Collins", position : "RB", team: "Baltimore Ravens", logo : "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", alt : "Bal"},
{name : "T.J. Yeldon", position : "RB", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
{name : "Latavius Murray", position : "RB", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
{name : "Tevin Coleman", position : "RB", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
{name : "Kenyan Drake", position : "RB", team: "Miami Dolphins", logo : "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", alt : "Mia"},
{name : "Saquon Barkley", position : "RB", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
{name : "Derrick Henry", position : "RB", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
{name : "Nyheim Hines", position : "RB", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
{name : "Marlon Mack", position : "RB", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
{name : "Matt Breida", position : "RB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
{name : "Peyton Barber", position : "RB", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
{name : "Chris Carson", position : "RB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
{name : "Tarik Cohen", position : "RB", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
{name : "Mike Davis", position : "RB", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
{name : "Alfred Morris", position : "RB", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
{name : "Phillip Lindsay", position : "RB", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
{name : "Royce Freeman", position : "RB", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
{name : "Antonio Brown", position : "WR", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
{name : "Odell Beckham", position : "WR", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
{name : "Julio Jones", position : "WR", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
{name : "DeAndre Hopkins", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
{name : "Allen Robinson", position : "WR", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
{name : "A.J. Green", position : "WR", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
{name : "Keenan Allen", position : "WR", team: "San Diego Chargers", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/NFL_Chargers_logo.svg", alt : "LAC"},
{name : "Alshon Jeffery", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
{name : "Jordy Nelson", position : "WR", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
{name : "Brandon Marshall", position : "WR", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
{name : "Mike Evans", position : "WR", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
{name : "Michael Thomas", position : "WR", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
{name : "T.Y. Hilton", position : "WR", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
{name : "Doug Baldwin", position : "WR", team: "Seattle Seahawks", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg", alt : "Sea"},
{name : "Amari Cooper", position : "WR", team: "Dallas Cowboys", logo : "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg", alt : "Dal"},
{name : "Brandin Cooks", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
{name : "Michael Crabtree", position : "WR", team: "Baltimore Ravens", logo : "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", alt : "Bal"},
{name : "Demaryius Thomas", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
{name : "Larry Fitzgerald", position : "WR", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
{name : "Christian Kirk", position : "WR", team: "Arizona Cardinals", logo : "https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg", alt : "Ari"},
{name : "Emmanuel Sanders", position : "WR", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
{name : "Terrelle Pryor", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
{name : "Davante Adams", position : "WR", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
{name : "Jamison Crowder", position : "WR", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
{name : "Kelvin Benjamin", position : "WR", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
{name : "Golden Tate", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
{name : "Jarvis Landry", position : "WR", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
{name : "Kenny Stills", position : "WR", team: "Miami Dolphins", logo : "https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg", alt : "Mia"},
{name : "Tyreek Hill", position : "WR", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
{name : "Stefon Diggs", position : "WR", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
{name : "Adam Thielen", position : "WR", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
{name : "Marvin Jones", position : "WR", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
{name : "Kenny Golladay", position : "WR", team: "Detroit Lions", logo : "https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg", alt : "Det"},
{name : "JuJu Smith-Schuster", position : "WR", team: "Pittsburgh Steelers", logo : "https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg", alt : "Pit"},
{name : "Robby Anderson", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
{name : "Devin Funchess", position : "WR", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
{name : "Nelson Agholor", position : "WR", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
{name : "Cooper Kupp", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
{name : "Robert Woods", position : "WR", team: "Los Angeles Rams", logo : "https://upload.wikimedia.org/wikipedia/en/8/8b/NFL_Rams_logo.svg", alt : "LAR"},
{name : "Sammy Watkins", position : "WR", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
{name : "Marquise Goodwin", position : "WR", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
{name : "Jermaine Kearse", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
{name : "Dez Bryant", position : "WR", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
{name : "Paul Richardson", position : "WR", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
{name : "Corey Davis", position : "WR", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
{name : "Will Fuller", position : "WR", team: "Houston Texans", logo : "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg", alt : "Hou"},
{name : "Dede Westbrook", position : "WR", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
{name : "Keelan Cole", position : "WR", team: "Jacksonville Jaguars", logo : "https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg", alt : "Jac"},
{name : "Calvin Ridley", position : "WR", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"},
{name : "Tyler Boyd", position : "WR", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
{name : "Julian Edelman", position : "WR", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
{name : "Josh Gordon", position : "WR", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
{name : "Quincy Enunwa", position : "WR", team: "New York Jets", logo : "https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg", alt : "NYJ"},
{name : "John Brown", position : "WR", team: "Baltimore Ravens", logo : "https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg", alt : "Bal"},
{name : "DeSean Jackson", position : "WR", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
{name : "Tre'Quan Smith", position : "WR", team: "New Orleans Saints", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg", alt : "NO"},
{name : "Courtland Sutton", position : "WR", team: "Denver Broncos", logo : "https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg", alt : "Den"},
{name : "Rob Gronkowski", position : "TE", team: "New England Patriots", logo : "https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg", alt : "NE"},
{name : "Jordan Reed", position : "TE", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
{name : "Greg Olsen", position : "TE", team : "Carolina Panthers", logo : "https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg", alt : "Car"},
{name : "Travis Kelce", position : "TE", team: "Kansas City Chiefs", logo : "https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg", alt : "KC"},
{name : "Charles Clay", position : "TE", team: "Buffalo Bills", logo : "https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg", alt : "Buf"},
{name : "Jimmy Graham", position : "TE", team: "Green Bay Packers", logo : "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg", alt : "GB"},
{name : "Delanie Walker", position : "TE", team: "Tennessee Titans", logo : "https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg", alt : "Ten"},
{name : "Tyler Eifert", position : "TE", team: "Cincinnati Bengals", logo : "https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg", alt : "Cin"},
{name : "Jack Doyle", position : "TE", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
{name : "Zach Ertz", position : "TE", team: "Philadelphia Eagles", logo : "https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg", alt : "Phi"},
{name : "Kyle Rudolph", position : "TE", team: "Minnesota Vikings", logo : "https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg", alt : "Min"},
{name : "Eric Ebron", position : "TE", team: "Indianapolis Colts", logo : "https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg", alt : "Ind"},
{name : "Evan Engram", position : "TE", team: "New York Giants", logo : "https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg", alt : "NYG"},
{name : "Cameron Brate", position : "TE", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
{name : "Vernon Davis", position : "TE", team: "Washington Redskins", logo : "https://upload.wikimedia.org/wikipedia/en/6/63/Washington_Redskins_logo.svg", alt : "Was"},
{name : "O.J. Howard", position : "TE", team: "Tampa Bay Buccaneers", logo : "https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg", alt : "TB"},
{name : "George Kittle", position : "TE", team: "San Francisco 49ers", logo : "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg", alt : "SF"},
{name : "Jared Cook", position : "TE", team: "Oakland Raiders", logo : "https://upload.wikimedia.org/wikipedia/en/e/ec/Oakland_Raiders_logo.svg", alt : "Oak"},
{name : "Trey Burton", position : "TE", team: "Chicago Bears", logo : "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg", alt : "Chi"},
{name : "David Njoku", position : "TE", team: "Cleveland Browns", logo : "https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg", alt : "Cle"},
{name : "Austin Hooper", position : "TE", team: "Atlanta Falcons", logo : "https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg", alt : "Atl"}
];