qb_stats =
[
  {
    "Player": "",
    "Team": "",
    "ATT": "",
    "CMP": "",
    "PASS YDS": "",
    "PASS TDS": "",
    "INTS": "",
    "RUSH YDS": "",
    "RUSH TDS": "",
    "FL": "",
    "FPTS": ""
  },
  {
    "Player": "Aaron Rodgers",
    "Team": "GB",
    "ATT": 60.7,
    "CMP": 395.9,
    "PASS YDS": 4438.1,
    "PASS TDS": 35.4,
    "INTS": 8.3,
    "RUSH YDS": 340.2,
    "RUSH TDS": 2.5,
    "FL": 3.9,
    "FPTS": 343.9
  },
  {
    "Player": "Tom Brady",
    "Team": "NE",
    "ATT": 35.5,
    "CMP": 393,
    "PASS YDS": 4697.4,
    "PASS TDS": 35.4,
    "INTS": 8.3,
    "RUSH YDS": 85.3,
    "RUSH TDS": 1.3,
    "FL": 2.8,
    "FPTS": 323.9
  },
  {
    "Player": "Drew Brees",
    "Team": "NO",
    "ATT": 22.8,
    "CMP": 439.3,
    "PASS YDS": 4927.6,
    "PASS TDS": 33.3,
    "INTS": 14.4,
    "RUSH YDS": 45.2,
    "RUSH TDS": 1.3,
    "FL": 3.8,
    "FPTS": 306
  },
  {
    "Player": "Matt Ryan",
    "Team": "ATL",
    "ATT": 34.8,
    "CMP": 376.6,
    "PASS YDS": 4655.9,
    "PASS TDS": 32.7,
    "INTS": 11,
    "RUSH YDS": 102.2,
    "RUSH TDS": 0.8,
    "FL": 2.9,
    "FPTS": 304.2
  },
  {
    "Player": "Russell Wilson",
    "Team": "SEA",
    "ATT": 81.2,
    "CMP": 343.2,
    "PASS YDS": 4102.8,
    "PASS TDS": 26.9,
    "INTS": 11.8,
    "RUSH YDS": 378.6,
    "RUSH TDS": 2.1,
    "FL": 2.8,
    "FPTS": 293.4
  },
  {
    "Player": "Andrew Luck",
    "Team": "IND",
    "ATT": 62.9,
    "CMP": 340.5,
    "PASS YDS": 4040.8,
    "PASS TDS": 29.2,
    "INTS": 15.4,
    "RUSH YDS": 306.1,
    "RUSH TDS": 2.1,
    "FL": 3.1,
    "FPTS": 284.7
  },
  {
    "Player": "Cam Newton",
    "Team": "CAR",
    "ATT": 84.7,
    "CMP": 305.6,
    "PASS YDS": 3794.9,
    "PASS TDS": 24.3,
    "INTS": 13.5,
    "RUSH YDS": 408.3,
    "RUSH TDS": 4.8,
    "FL": 4.2,
    "FPTS": 283.3
  },
  {
    "Player": "Jameis Winston",
    "Team": "TB",
    "ATT": 50,
    "CMP": 357.1,
    "PASS YDS": 4287.9,
    "PASS TDS": 28.2,
    "INTS": 16.1,
    "RUSH YDS": 182.6,
    "RUSH TDS": 2.5,
    "FL": 3.9,
    "FPTS": 277.8
  },
  {
    "Player": "Marcus Mariota",
    "Team": "TEN",
    "ATT": 58.2,
    "CMP": 319.7,
    "PASS YDS": 3797.4,
    "PASS TDS": 26.5,
    "INTS": 12.4,
    "RUSH YDS": 330.6,
    "RUSH TDS": 2.1,
    "FL": 3.6,
    "FPTS": 271.2
  },
  {
    "Player": "Kirk Cousins",
    "Team": "WAS",
    "ATT": 33.4,
    "CMP": 385.9,
    "PASS YDS": 4530.3,
    "PASS TDS": 24.9,
    "INTS": 13.3,
    "RUSH YDS": 89.9,
    "RUSH TDS": 2.5,
    "FL": 4.4,
    "FPTS": 269.3
  },
  {
    "Player": "Dak Prescott",
    "Team": "DAL",
    "ATT": 59.1,
    "CMP": 319.2,
    "PASS YDS": 3744.3,
    "PASS TDS": 24.7,
    "INTS": 9,
    "RUSH YDS": 276.8,
    "RUSH TDS": 3.1,
    "FL": 3.9,
    "FPTS": 269
  },
  {
    "Player": "Matthew Stafford",
    "Team": "DET",
    "ATT": 37.1,
    "CMP": 380.7,
    "PASS YDS": 4180.4,
    "PASS TDS": 25.2,
    "INTS": 12.4,
    "RUSH YDS": 158.5,
    "RUSH TDS": 1.8,
    "FL": 2.8,
    "FPTS": 264.2
  },
  {
    "Player": "Ben Roethlisberger",
    "Team": "PIT",
    "ATT": 22.6,
    "CMP": 360.1,
    "PASS YDS": 4232.5,
    "PASS TDS": 29.5,
    "INTS": 14,
    "RUSH YDS": 42.5,
    "RUSH TDS": 0.8,
    "FL": 2.2,
    "FPTS": 263.5
  },
  {
    "Player": "Tyrod Taylor",
    "Team": "BUF",
    "ATT": 92.5,
    "CMP": 280.8,
    "PASS YDS": 3147.5,
    "PASS TDS": 19.5,
    "INTS": 8.9,
    "RUSH YDS": 553.3,
    "RUSH TDS": 4.4,
    "FL": 3.2,
    "FPTS": 261.5
  },
  {
    "Player": "Andy Dalton",
    "Team": "CIN",
    "ATT": 48.6,
    "CMP": 346.9,
    "PASS YDS": 3995.3,
    "PASS TDS": 24.1,
    "INTS": 11.1,
    "RUSH YDS": 164.3,
    "RUSH TDS": 2.5,
    "FL": 3.7,
    "FPTS": 257.7
  },
  {
    "Player": "Philip Rivers",
    "Team": "LAC",
    "ATT": 16.8,
    "CMP": 361.1,
    "PASS YDS": 4308.4,
    "PASS TDS": 30.5,
    "INTS": 15.7,
    "RUSH YDS": 40.5,
    "RUSH TDS": 0.2,
    "FL": 5.5,
    "FPTS": 257.2
  },
  {
    "Player": "Derek Carr",
    "Team": "OAK",
    "ATT": 35.3,
    "CMP": 361.9,
    "PASS YDS": 4082.9,
    "PASS TDS": 27.7,
    "INTS": 11.1,
    "RUSH YDS": 86.7,
    "RUSH TDS": 0.6,
    "FL": 3.8,
    "FPTS": 256.8
  },
  {
    "Player": "Blake Bortles",
    "Team": "JAC",
    "ATT": 55.8,
    "CMP": 329.1,
    "PASS YDS": 3659.3,
    "PASS TDS": 22.8,
    "INTS": 15.4,
    "RUSH YDS": 315.4,
    "RUSH TDS": 2.2,
    "FL": 4.4,
    "FPTS": 242.5
  },
  {
    "Player": "Eli Manning",
    "Team": "NYG",
    "ATT": 18.9,
    "CMP": 367.7,
    "PASS YDS": 4156.3,
    "PASS TDS": 27.2,
    "INTS": 15.2,
    "RUSH YDS": 30.4,
    "RUSH TDS": 0.2,
    "FL": 4.4,
    "FPTS": 240.3
  },
  {
    "Player": "Carson Wentz",
    "Team": "PHI",
    "ATT": 46.9,
    "CMP": 354,
    "PASS YDS": 3861.5,
    "PASS TDS": 22.3,
    "INTS": 14.1,
    "RUSH YDS": 171.4,
    "RUSH TDS": 1.9,
    "FL": 3.6,
    "FPTS": 236.8
  },
  {
    "Player": "Carson Palmer",
    "Team": "ARI",
    "ATT": 16.2,
    "CMP": 359.2,
    "PASS YDS": 4139.7,
    "PASS TDS": 25.2,
    "INTS": 15.3,
    "RUSH YDS": 34.9,
    "RUSH TDS": 0.3,
    "FL": 4.4,
    "FPTS": 232.6
  },
  {
    "Player": "Joe Flacco",
    "Team": "BAL",
    "ATT": 23.3,
    "CMP": 389.8,
    "PASS YDS": 4078.3,
    "PASS TDS": 22,
    "INTS": 15.5,
    "RUSH YDS": 51.4,
    "RUSH TDS": 1.6,
    "FL": 3,
    "FPTS": 229
  },
  {
    "Player": "Alex Smith",
    "Team": "KC",
    "ATT": 55.2,
    "CMP": 325,
    "PASS YDS": 3514.5,
    "PASS TDS": 19.7,
    "INTS": 10,
    "RUSH YDS": 207,
    "RUSH TDS": 2.6,
    "FL": 4.5,
    "FPTS": 226.6
  },
  {
    "Player": "Sam Bradford",
    "Team": "MIN",
    "ATT": 21.2,
    "CMP": 355.1,
    "PASS YDS": 3738.1,
    "PASS TDS": 21.5,
    "INTS": 9.9,
    "RUSH YDS": 46.5,
    "RUSH TDS": 0.3,
    "FL": 4,
    "FPTS": 213.8
  },
  {
    "Player": "Jay Cutler",
    "Team": "MIA",
    "ATT": 32.2,
    "CMP": 289.3,
    "PASS YDS": 3327.4,
    "PASS TDS": 21.7,
    "INTS": 14.2,
    "RUSH YDS": 130.1,
    "RUSH TDS": 1,
    "FL": 3.9,
    "FPTS": 203.2
  },
  {
    "Player": "Brian Hoyer",
    "Team": "SF",
    "ATT": 27.7,
    "CMP": 281,
    "PASS YDS": 3162.9,
    "PASS TDS": 17.5,
    "INTS": 11.5,
    "RUSH YDS": 69.8,
    "RUSH TDS": 0.5,
    "FL": 4.6,
    "FPTS": 174
  },
  {
    "Player": "Jared Goff",
    "Team": "LAR",
    "ATT": 23.6,
    "CMP": 291.3,
    "PASS YDS": 3203.9,
    "PASS TDS": 16.7,
    "INTS": 15.9,
    "RUSH YDS": 67.3,
    "RUSH TDS": 0.9,
    "FL": 3.6,
    "FPTS": 168.2
  },
  {
    "Player": "Mike Glennon",
    "Team": "CHI",
    "ATT": 25.6,
    "CMP": 241.2,
    "PASS YDS": 2773.3,
    "PASS TDS": 16.4,
    "INTS": 11.4,
    "RUSH YDS": 94.4,
    "RUSH TDS": 0.7,
    "FL": 2.6,
    "FPTS": 162
  },
  {
    "Player": "Trevor Siemian",
    "Team": "DEN",
    "ATT": 22.1,
    "CMP": 252,
    "PASS YDS": 2856.1,
    "PASS TDS": 15.4,
    "INTS": 11.1,
    "RUSH YDS": 66.1,
    "RUSH TDS": 0.5,
    "FL": 2.9,
    "FPTS": 157.3
  },
  {
    "Player": "Josh McCown",
    "Team": "NYJ",
    "ATT": 29.2,
    "CMP": 221.9,
    "PASS YDS": 2471.1,
    "PASS TDS": 12.7,
    "INTS": 12.2,
    "RUSH YDS": 104.4,
    "RUSH TDS": 0.9,
    "FL": 3.4,
    "FPTS": 134.1
  },
  {
    "Player": "Deshaun Watson",
    "Team": "HOU",
    "ATT": 35.8,
    "CMP": 170.6,
    "PASS YDS": 1868,
    "PASS TDS": 10.3,
    "INTS": 8.4,
    "RUSH YDS": 148,
    "RUSH TDS": 1.1,
    "FL": 1.1,
    "FPTS": 118.2
  },
  {
    "Player": "Tom Savage",
    "Team": "HOU",
    "ATT": 16.8,
    "CMP": 153.8,
    "PASS YDS": 1652.8,
    "PASS TDS": 9.3,
    "INTS": 6.9,
    "RUSH YDS": 60.6,
    "RUSH TDS": 0.4,
    "FL": 1.8,
    "FPTS": 94.5
  },
  {
    "Player": "Cody Kessler",
    "Team": "CLE",
    "ATT": 16.8,
    "CMP": 150.2,
    "PASS YDS": 1661.5,
    "PASS TDS": 8.5,
    "INTS": 7,
    "RUSH YDS": 43.9,
    "RUSH TDS": 0.5,
    "FL": 0.7,
    "FPTS": 92.4
  },
  {
    "Player": "DeShone Kizer",
    "Team": "CLE",
    "ATT": 23.3,
    "CMP": 141.7,
    "PASS YDS": 1568.5,
    "PASS TDS": 8.1,
    "INTS": 8,
    "RUSH YDS": 91.9,
    "RUSH TDS": 0.8,
    "FL": 1.2,
    "FPTS": 90.5
  },
  {
    "Player": "Paxton Lynch",
    "Team": "DEN",
    "ATT": 13.9,
    "CMP": 89.4,
    "PASS YDS": 1017.9,
    "PASS TDS": 5.6,
    "INTS": 3.6,
    "RUSH YDS": 46.5,
    "RUSH TDS": 0.4,
    "FL": 0.8,
    "FPTS": 61.3
  },
  {
    "Player": "Mitch Trubisky",
    "Team": "CHI",
    "ATT": 10.5,
    "CMP": 84.3,
    "PASS YDS": 961.7,
    "PASS TDS": 5.6,
    "INTS": 4.8,
    "RUSH YDS": 39,
    "RUSH TDS": 0.2,
    "FL": 1.3,
    "FPTS": 53.7
  },
  {
    "Player": "Brock Osweiler",
    "Team": "CLE",
    "ATT": 6.8,
    "CMP": 65,
    "PASS YDS": 702,
    "PASS TDS": 3.5,
    "INTS": 3,
    "RUSH YDS": 26.8,
    "RUSH TDS": 0.3,
    "FL": 1.1,
    "FPTS": 38.1
  },
  {
    "Player": "Bryce Petty",
    "Team": "NYJ",
    "ATT": 5.5,
    "CMP": 49.3,
    "PASS YDS": 548,
    "PASS TDS": 3,
    "INTS": 3.3,
    "RUSH YDS": 16.6,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 29.1
  },
  {
    "Player": "Christian Hackenberg",
    "Team": "NYJ",
    "ATT": 4.9,
    "CMP": 54.2,
    "PASS YDS": 591.6,
    "PASS TDS": 2.5,
    "INTS": 3.8,
    "RUSH YDS": 17.5,
    "RUSH TDS": 0.1,
    "FL": 0.3,
    "FPTS": 27.7
  },
  {
    "Player": "Sean Mannion",
    "Team": "LAR",
    "ATT": 3.9,
    "CMP": 36.3,
    "PASS YDS": 402.1,
    "PASS TDS": 2.5,
    "INTS": 1.3,
    "RUSH YDS": 9.7,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 24.5
  },
  {
    "Player": "Matt Barkley",
    "Team": "SF",
    "ATT": 2.5,
    "CMP": 35.5,
    "PASS YDS": 416.7,
    "PASS TDS": 2.5,
    "INTS": 2.1,
    "RUSH YDS": 4.8,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 22.9
  },
  {
    "Player": "Matt Moore",
    "Team": "MIA",
    "ATT": 2.6,
    "CMP": 30.4,
    "PASS YDS": 346.4,
    "PASS TDS": 2,
    "INTS": 1.3,
    "RUSH YDS": 6.7,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 19.8
  },
  {
    "Player": "Patrick Mahomes",
    "Team": "KC",
    "ATT": 4.4,
    "CMP": 29.2,
    "PASS YDS": 321.4,
    "PASS TDS": 1.6,
    "INTS": 1.2,
    "RUSH YDS": 16.6,
    "RUSH TDS": 0.1,
    "FL": 0,
    "FPTS": 19.2
  },
  {
    "Player": "Teddy Bridgewater",
    "Team": "MIN",
    "ATT": 3.5,
    "CMP": 24.4,
    "PASS YDS": 271.6,
    "PASS TDS": 1.8,
    "INTS": 1.2,
    "RUSH YDS": 10.2,
    "RUSH TDS": 0.1,
    "FL": 0,
    "FPTS": 17.2
  },
  {
    "Player": "Nathan Peterman",
    "Team": "BUF",
    "ATT": 2,
    "CMP": 21,
    "PASS YDS": 237,
    "PASS TDS": 2,
    "INTS": 1,
    "RUSH YDS": 4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 15.9
  },
  {
    "Player": "Brandon Weeden",
    "Team": "HOU",
    "ATT": 3.2,
    "CMP": 19.8,
    "PASS YDS": 222.1,
    "PASS TDS": 1.3,
    "INTS": 1.3,
    "RUSH YDS": 13.6,
    "RUSH TDS": 0.1,
    "FL": 0,
    "FPTS": 13.7
  },
  {
    "Player": "Blaine Gabbert",
    "Team": "ARI",
    "ATT": 2,
    "CMP": 23.5,
    "PASS YDS": 270,
    "PASS TDS": 1,
    "INTS": 1,
    "RUSH YDS": 4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 13.2
  },
  {
    "Player": "Kevin Hogan",
    "Team": "CLE",
    "ATT": 3,
    "CMP": 17.7,
    "PASS YDS": 194.4,
    "PASS TDS": 1.1,
    "INTS": 0.8,
    "RUSH YDS": 19.4,
    "RUSH TDS": 0.1,
    "FL": 0,
    "FPTS": 13.1
  },
  {
    "Player": "Scott Tolzien",
    "Team": "IND",
    "ATT": 1.6,
    "CMP": 21,
    "PASS YDS": 234.8,
    "PASS TDS": 1.2,
    "INTS": 1,
    "RUSH YDS": 3.8,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 12.6
  },
  {
    "Player": "Landry Jones",
    "Team": "PIT",
    "ATT": 1.9,
    "CMP": 18.7,
    "PASS YDS": 212.6,
    "PASS TDS": 1.2,
    "INTS": 0.9,
    "RUSH YDS": 5.7,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 12.5
  },
  {
    "Player": "Drew Stanton",
    "Team": "ARI",
    "ATT": 1.4,
    "CMP": 18.7,
    "PASS YDS": 210,
    "PASS TDS": 1.4,
    "INTS": 1,
    "RUSH YDS": 4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 12.4
  },
  {
    "Player": "C.J. Beathard",
    "Team": "SF",
    "ATT": 1.8,
    "CMP": 20.3,
    "PASS YDS": 203.1,
    "PASS TDS": 1.1,
    "INTS": 1.3,
    "RUSH YDS": 6.8,
    "RUSH TDS": 0.1,
    "FL": 0,
    "FPTS": 11.2
  },
  {
    "Player": "Chad Henne",
    "Team": "JAC",
    "ATT": 1.6,
    "CMP": 15.4,
    "PASS YDS": 177.9,
    "PASS TDS": 0.9,
    "INTS": 0.7,
    "RUSH YDS": 6.2,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 10.2
  },
  {
    "Player": "Derek Anderson",
    "Team": "CAR",
    "ATT": 2.3,
    "CMP": 15.1,
    "PASS YDS": 175.2,
    "PASS TDS": 0.9,
    "INTS": 0.6,
    "RUSH YDS": 4.2,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 9.9
  },
  {
    "Player": "Matt Cassel",
    "Team": "TEN",
    "ATT": 1.8,
    "CMP": 14.4,
    "PASS YDS": 166.6,
    "PASS TDS": 0.7,
    "INTS": 0.7,
    "RUSH YDS": 5.5,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 8.6
  },
  {
    "Player": "Nick Foles",
    "Team": "PHI",
    "ATT": 1,
    "CMP": 12,
    "PASS YDS": 139.5,
    "PASS TDS": 0.6,
    "INTS": 0.2,
    "RUSH YDS": 3.3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.9
  },
  {
    "Player": "AJ McCarron",
    "Team": "CIN",
    "ATT": 1.5,
    "CMP": 11.3,
    "PASS YDS": 133.3,
    "PASS TDS": 0.7,
    "INTS": 0.4,
    "RUSH YDS": 3.5,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.7
  },
  {
    "Player": "Brett Hundley",
    "Team": "GB",
    "ATT": 1.1,
    "CMP": 11.6,
    "PASS YDS": 136.8,
    "PASS TDS": 0.7,
    "INTS": 0.5,
    "RUSH YDS": 3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.7
  },
  {
    "Player": "Case Keenum",
    "Team": "MIN",
    "ATT": 1.3,
    "CMP": 11,
    "PASS YDS": 120.1,
    "PASS TDS": 0.7,
    "INTS": 0.3,
    "RUSH YDS": 3.8,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.7
  },
  {
    "Player": "Geno Smith",
    "Team": "NYG",
    "ATT": 1.7,
    "CMP": 11.2,
    "PASS YDS": 130.4,
    "PASS TDS": 0.7,
    "INTS": 0.6,
    "RUSH YDS": 5.8,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.5
  },
  {
    "Player": "Jimmy Garoppolo",
    "Team": "NE",
    "ATT": 0.9,
    "CMP": 10.1,
    "PASS YDS": 119.5,
    "PASS TDS": 0.7,
    "INTS": 0.1,
    "RUSH YDS": 1.5,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.4
  },
  {
    "Player": "Ryan Mallett",
    "Team": "BAL",
    "ATT": 1.1,
    "CMP": 11.7,
    "PASS YDS": 131.4,
    "PASS TDS": 0.6,
    "INTS": 0.7,
    "RUSH YDS": 3.3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.8
  },
  {
    "Player": "Kellen Clemens",
    "Team": "LAC",
    "ATT": 1.5,
    "CMP": 10.7,
    "PASS YDS": 121.7,
    "PASS TDS": 0.7,
    "INTS": 0.7,
    "RUSH YDS": 4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.7
  },
  {
    "Player": "Trevone Boykin",
    "Team": "SEA",
    "ATT": 1.8,
    "CMP": 10.6,
    "PASS YDS": 124.6,
    "PASS TDS": 0.4,
    "INTS": 0.3,
    "RUSH YDS": 6,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.7
  },
  {
    "Player": "Colt McCoy",
    "Team": "WAS",
    "ATT": 1.2,
    "CMP": 9.2,
    "PASS YDS": 106.3,
    "PASS TDS": 0.6,
    "INTS": 0.2,
    "RUSH YDS": 2.7,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.6
  },
  {
    "Player": "Jake Rudock",
    "Team": "DET",
    "ATT": 1.1,
    "CMP": 10.9,
    "PASS YDS": 123.8,
    "PASS TDS": 0.7,
    "INTS": 0.6,
    "RUSH YDS": 1.4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.5
  },
  {
    "Player": "Connor Cook",
    "Team": "OAK",
    "ATT": 1.7,
    "CMP": 10.9,
    "PASS YDS": 123.1,
    "PASS TDS": 0.5,
    "INTS": 0.5,
    "RUSH YDS": 5.4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.4
  },
  {
    "Player": "Ryan Fitzpatrick",
    "Team": "TB",
    "ATT": 1.3,
    "CMP": 9.8,
    "PASS YDS": 112.8,
    "PASS TDS": 0.3,
    "INTS": 0.4,
    "RUSH YDS": 5.2,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 5.6
  },
  {
    "Player": "T.J. Yates",
    "Team": "BUF",
    "ATT": 0.9,
    "CMP": 10.5,
    "PASS YDS": 114.5,
    "PASS TDS": 0.4,
    "INTS": 0.4,
    "RUSH YDS": 2,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 5.6
  },
  {
    "Player": "Cardale Jones",
    "Team": "LAC",
    "ATT": 2.2,
    "CMP": 10.3,
    "PASS YDS": 109.2,
    "PASS TDS": 0.5,
    "INTS": 0.7,
    "RUSH YDS": 4.4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 5.4
  },
  {
    "Player": "Kellen Moore",
    "Team": "DAL",
    "ATT": 0.9,
    "CMP": 9.7,
    "PASS YDS": 112.9,
    "PASS TDS": 0.3,
    "INTS": 0.2,
    "RUSH YDS": 1.8,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 5.4
  },
  {
    "Player": "Matt Schaub",
    "Team": "ATL",
    "ATT": 0.9,
    "CMP": 7.6,
    "PASS YDS": 83.5,
    "PASS TDS": 0.4,
    "INTS": 0.4,
    "RUSH YDS": 2.5,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4.6
  },
  {
    "Player": "Chase Daniel",
    "Team": "NO",
    "ATT": 1,
    "CMP": 6.4,
    "PASS YDS": 76.3,
    "PASS TDS": 0.2,
    "INTS": 0.3,
    "RUSH YDS": 1.6,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 3.5
  },
  {
    "Player": "Mark Sanchez",
    "Team": "CHI",
    "ATT": 0,
    "CMP": 0.5,
    "PASS YDS": 3,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0.1
  },
  {
    "Player": "Jacoby Brissett",
    "Team": "NE",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Josh Johnson",
    "Team": "NYG",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Alex Tanney",
    "Team": "TEN",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "David Fales",
    "Team": "MIA",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Joe Webb",
    "Team": "CAR",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Matt McGloin",
    "Team": "PHI",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Matt Simms",
    "Team": "ATL",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "",
    "Team": "",
    "ATT": "",
    "CMP": "",
    "PASS YDS": "",
    "PASS TDS": "",
    "INTS": "",
    "RUSH YDS": "",
    "RUSH TDS": "",
    "FL": "",
    "FPTS": ""
  },
  {
    "Player": "",
    "Team": "",
    "ATT": "",
    "CMP": "",
    "PASS YDS": "",
    "PASS TDS": "",
    "INTS": "",
    "RUSH YDS": "",
    "RUSH TDS": "",
    "FL": "",
    "FPTS": ""
  }
]