qb_stats =
[
  {
    "Player": "Aaron Rodgers",
    "Team": "GB",
    "ATT": 58.9,
    "CMP": 376.1,
    "PASS YDS": 4167.1,
    "PASS TDS": 33.8,
    "INTS": 9.2,
    "RUSH YDS": 309.5,
    "RUSH TDS": 2.1,
    "FL": 2.9,
    "FPTS": 321.1
  },
  {
    "Player": "Tom Brady",
    "Team": "NE",
    "ATT": 27.7,
    "CMP": 383.8,
    "PASS YDS": 4592,
    "PASS TDS": 32.4,
    "INTS": 8.7,
    "RUSH YDS": 41,
    "RUSH TDS": 0.9,
    "FL": 2.9,
    "FPTS": 299.5
  },
  {
    "Player": "Russell Wilson",
    "Team": "SEA",
    "ATT": 90.4,
    "CMP": 325.1,
    "PASS YDS": 3825.5,
    "PASS TDS": 26.1,
    "INTS": 12.5,
    "RUSH YDS": 503.1,
    "RUSH TDS": 3.2,
    "FL": 3.4,
    "FPTS": 294.8
  },
  {
    "Player": "Deshaun Watson",
    "Team": "HOU",
    "ATT": 76.7,
    "CMP": 309,
    "PASS YDS": 3779.2,
    "PASS TDS": 27.3,
    "INTS": 16,
    "RUSH YDS": 442,
    "RUSH TDS": 3.5,
    "FL": 3.2,
    "FPTS": 287.1
  },
  {
    "Player": "Cam Newton",
    "Team": "CAR",
    "ATT": 120,
    "CMP": 299.6,
    "PASS YDS": 3480.8,
    "PASS TDS": 22.3,
    "INTS": 14.5,
    "RUSH YDS": 621.4,
    "RUSH TDS": 5,
    "FL": 2.7,
    "FPTS": 286.5
  },
  {
    "Player": "Drew Brees",
    "Team": "NO",
    "ATT": 26.7,
    "CMP": 392,
    "PASS YDS": 4520.4,
    "PASS TDS": 29,
    "INTS": 12.6,
    "RUSH YDS": 57.2,
    "RUSH TDS": 1.4,
    "FL": 2.8,
    "FPTS": 280.2
  },
  {
    "Player": "Andrew Luck",
    "Team": "IND",
    "ATT": 56.6,
    "CMP": 342.3,
    "PASS YDS": 3970,
    "PASS TDS": 26.2,
    "INTS": 14.7,
    "RUSH YDS": 275.9,
    "RUSH TDS": 2,
    "FL": 3.2,
    "FPTS": 267.2
  },
  {
    "Player": "Ben Roethlisberger",
    "Team": "PIT",
    "ATT": 23.6,
    "CMP": 365.7,
    "PASS YDS": 4370.1,
    "PASS TDS": 28.7,
    "INTS": 14.7,
    "RUSH YDS": 60.3,
    "RUSH TDS": 0.7,
    "FL": 2.7,
    "FPTS": 264.9
  },
  {
    "Player": "Matthew Stafford",
    "Team": "DET",
    "ATT": 34.8,
    "CMP": 372.3,
    "PASS YDS": 4239.5,
    "PASS TDS": 26.7,
    "INTS": 12,
    "RUSH YDS": 127.7,
    "RUSH TDS": 1,
    "FL": 3.5,
    "FPTS": 264.1
  },
  {
    "Player": "Alex Smith",
    "Team": "WAS",
    "ATT": 58,
    "CMP": 343.2,
    "PASS YDS": 3914.1,
    "PASS TDS": 24.1,
    "INTS": 9.1,
    "RUSH YDS": 259,
    "RUSH TDS": 1.7,
    "FL": 3.8,
    "FPTS": 263.3
  },
  {
    "Player": "Jimmy Garoppolo",
    "Team": "SF",
    "ATT": 39.8,
    "CMP": 362.1,
    "PASS YDS": 4292.2,
    "PASS TDS": 24.5,
    "INTS": 12.2,
    "RUSH YDS": 116.1,
    "RUSH TDS": 1.6,
    "FL": 2.9,
    "FPTS": 260.5
  },
  {
    "Player": "Kirk Cousins",
    "Team": "MIN",
    "ATT": 49,
    "CMP": 353.5,
    "PASS YDS": 4042.2,
    "PASS TDS": 25.6,
    "INTS": 13.5,
    "RUSH YDS": 158.4,
    "RUSH TDS": 2.5,
    "FL": 3.7,
    "FPTS": 260.2
  },
  {
    "Player": "Philip Rivers",
    "Team": "LAC",
    "ATT": 19,
    "CMP": 355.4,
    "PASS YDS": 4335.9,
    "PASS TDS": 28.7,
    "INTS": 13.8,
    "RUSH YDS": 35,
    "RUSH TDS": 0.3,
    "FL": 3,
    "FPTS": 259.9
  },
  {
    "Player": "Matt Ryan",
    "Team": "ATL",
    "ATT": 34.4,
    "CMP": 360,
    "PASS YDS": 4240.1,
    "PASS TDS": 25.5,
    "INTS": 12.1,
    "RUSH YDS": 116.2,
    "RUSH TDS": 0.7,
    "FL": 2.8,
    "FPTS": 257.8
  },
  {
    "Player": "Jared Goff",
    "Team": "LAR",
    "ATT": 29.5,
    "CMP": 325.7,
    "PASS YDS": 3994.3,
    "PASS TDS": 27.2,
    "INTS": 11.4,
    "RUSH YDS": 78.3,
    "RUSH TDS": 1.1,
    "FL": 3.7,
    "FPTS": 252.6
  },
  {
    "Player": "Patrick Mahomes",
    "Team": "KC",
    "ATT": 57.8,
    "CMP": 340.9,
    "PASS YDS": 3884.2,
    "PASS TDS": 23.6,
    "INTS": 14.5,
    "RUSH YDS": 234.5,
    "RUSH TDS": 2,
    "FL": 2.8,
    "FPTS": 250.2
  },
  {
    "Player": "Marcus Mariota",
    "Team": "TEN",
    "ATT": 65.4,
    "CMP": 310.1,
    "PASS YDS": 3561.3,
    "PASS TDS": 21.9,
    "INTS": 14,
    "RUSH YDS": 349.7,
    "RUSH TDS": 3.1,
    "FL": 3.1,
    "FPTS": 249.4
  },
  {
    "Player": "Dak Prescott",
    "Team": "DAL",
    "ATT": 59.4,
    "CMP": 310.8,
    "PASS YDS": 3455.9,
    "PASS TDS": 21.6,
    "INTS": 12.4,
    "RUSH YDS": 324.1,
    "RUSH TDS": 3.7,
    "FL": 3,
    "FPTS": 248.2
  },
  {
    "Player": "Carson Wentz",
    "Team": "PHI",
    "ATT": 58.2,
    "CMP": 302.8,
    "PASS YDS": 3545.6,
    "PASS TDS": 25.3,
    "INTS": 10.4,
    "RUSH YDS": 230.9,
    "RUSH TDS": 1.6,
    "FL": 3.4,
    "FPTS": 248
  },
  {
    "Player": "Blake Bortles",
    "Team": "JAC",
    "ATT": 57.7,
    "CMP": 311.6,
    "PASS YDS": 3589.7,
    "PASS TDS": 21.6,
    "INTS": 13,
    "RUSH YDS": 325.4,
    "RUSH TDS": 2.3,
    "FL": 3.4,
    "FPTS": 243.4
  },
  {
    "Player": "Andy Dalton",
    "Team": "CIN",
    "ATT": 40.9,
    "CMP": 322.4,
    "PASS YDS": 3674.3,
    "PASS TDS": 23.5,
    "INTS": 13.4,
    "RUSH YDS": 135.4,
    "RUSH TDS": 1.4,
    "FL": 3.5,
    "FPTS": 228.8
  },
  {
    "Player": "Ryan Tannehill",
    "Team": "MIA",
    "ATT": 39.8,
    "CMP": 347.3,
    "PASS YDS": 3830.9,
    "PASS TDS": 22,
    "INTS": 14.7,
    "RUSH YDS": 164.2,
    "RUSH TDS": 1.3,
    "FL": 3.6,
    "FPTS": 228.5
  },
  {
    "Player": "Case Keenum",
    "Team": "DEN",
    "ATT": 40.4,
    "CMP": 342.8,
    "PASS YDS": 3805,
    "PASS TDS": 21.6,
    "INTS": 12.6,
    "RUSH YDS": 147.2,
    "RUSH TDS": 1.1,
    "FL": 3.5,
    "FPTS": 227.5
  },
  {
    "Player": "Derek Carr",
    "Team": "OAK",
    "ATT": 27.1,
    "CMP": 341.2,
    "PASS YDS": 3782.2,
    "PASS TDS": 24.4,
    "INTS": 13.2,
    "RUSH YDS": 75.8,
    "RUSH TDS": 0.5,
    "FL": 3.6,
    "FPTS": 226.2
  },
  {
    "Player": "Mitch Trubisky",
    "Team": "CHI",
    "ATT": 58.7,
    "CMP": 316.5,
    "PASS YDS": 3458.4,
    "PASS TDS": 20.1,
    "INTS": 13.9,
    "RUSH YDS": 289.4,
    "RUSH TDS": 2.2,
    "FL": 4.2,
    "FPTS": 224.5
  },
  {
    "Player": "Eli Manning",
    "Team": "NYG",
    "ATT": 15.3,
    "CMP": 367.8,
    "PASS YDS": 3912.9,
    "PASS TDS": 24.2,
    "INTS": 14.7,
    "RUSH YDS": 29.9,
    "RUSH TDS": 0.7,
    "FL": 3.4,
    "FPTS": 223.9
  },
  {
    "Player": "Jameis Winston",
    "Team": "TB",
    "ATT": 33.8,
    "CMP": 288.7,
    "PASS YDS": 3443.9,
    "PASS TDS": 20.3,
    "INTS": 12,
    "RUSH YDS": 132.6,
    "RUSH TDS": 1.1,
    "FL": 3.6,
    "FPTS": 208.1
  },
  {
    "Player": "Tyrod Taylor",
    "Team": "CLE",
    "ATT": 64.8,
    "CMP": 260.4,
    "PASS YDS": 2788.3,
    "PASS TDS": 15.8,
    "INTS": 7.6,
    "RUSH YDS": 342.9,
    "RUSH TDS": 2.9,
    "FL": 2.6,
    "FPTS": 205.8
  },
  {
    "Player": "Joe Flacco",
    "Team": "BAL",
    "ATT": 23.5,
    "CMP": 336.8,
    "PASS YDS": 3443.5,
    "PASS TDS": 19.9,
    "INTS": 13.7,
    "RUSH YDS": 64.7,
    "RUSH TDS": 1.1,
    "FL": 2.4,
    "FPTS": 198.2
  },
  {
    "Player": "Sam Darnold",
    "Team": "NYJ",
    "ATT": 36.7,
    "CMP": 279.4,
    "PASS YDS": 3192.2,
    "PASS TDS": 17.9,
    "INTS": 14,
    "RUSH YDS": 142.7,
    "RUSH TDS": 1.2,
    "FL": 3.2,
    "FPTS": 186.4
  },
  {
    "Player": "Sam Bradford",
    "Team": "ARI",
    "ATT": 13.4,
    "CMP": 218.2,
    "PASS YDS": 2439.1,
    "PASS TDS": 13.5,
    "INTS": 7.6,
    "RUSH YDS": 36,
    "RUSH TDS": 0.2,
    "FL": 1.6,
    "FPTS": 138.3
  },
  {
    "Player": "Josh Allen",
    "Team": "BUF",
    "ATT": 18.6,
    "CMP": 153.4,
    "PASS YDS": 2051.1,
    "PASS TDS": 11.6,
    "INTS": 10.8,
    "RUSH YDS": 105.3,
    "RUSH TDS": 0.9,
    "FL": 2.4,
    "FPTS": 118
  },
  {
    "Player": "Josh Rosen",
    "Team": "ARI",
    "ATT": 13.8,
    "CMP": 147.4,
    "PASS YDS": 1597,
    "PASS TDS": 8.3,
    "INTS": 6.4,
    "RUSH YDS": 49.3,
    "RUSH TDS": 0.4,
    "FL": 1.6,
    "FPTS": 88.3
  },
  {
    "Player": "Ryan Fitzpatrick",
    "Team": "TB",
    "ATT": 8.7,
    "CMP": 78.4,
    "PASS YDS": 1346.1,
    "PASS TDS": 7.2,
    "INTS": 5.2,
    "RUSH YDS": 58.5,
    "RUSH TDS": 0.4,
    "FL": 1.3,
    "FPTS": 78.3
  },
  {
    "Player": "Nathan Peterman",
    "Team": "BUF",
    "ATT": 17.7,
    "CMP": 135.4,
    "PASS YDS": 1196.1,
    "PASS TDS": 6.4,
    "INTS": 6.1,
    "RUSH YDS": 51.4,
    "RUSH TDS": 0.4,
    "FL": 0.8,
    "FPTS": 67.2
  },
  {
    "Player": "Baker Mayfield",
    "Team": "CLE",
    "ATT": 11.9,
    "CMP": 77.4,
    "PASS YDS": 951.7,
    "PASS TDS": 5.3,
    "INTS": 3.9,
    "RUSH YDS": 56.2,
    "RUSH TDS": 0.4,
    "FL": 1.1,
    "FPTS": 57.5
  },
  {
    "Player": "Nick Foles",
    "Team": "PHI",
    "ATT": 5.8,
    "CMP": 44.5,
    "PASS YDS": 468.5,
    "PASS TDS": 3.5,
    "INTS": 1.8,
    "RUSH YDS": 16.1,
    "RUSH TDS": 0.1,
    "FL": 0.3,
    "FPTS": 30.7
  },
  {
    "Player": "Lamar Jackson",
    "Team": "BAL",
    "ATT": 15.7,
    "CMP": 26.4,
    "PASS YDS": 304.5,
    "PASS TDS": 1.9,
    "INTS": 1.2,
    "RUSH YDS": 86.2,
    "RUSH TDS": 0.7,
    "FL": 1.2,
    "FPTS": 27.9
  },
  {
    "Player": "Josh McCown",
    "Team": "NYJ",
    "ATT": 5.7,
    "CMP": 41.3,
    "PASS YDS": 413.7,
    "PASS TDS": 2.5,
    "INTS": 2,
    "RUSH YDS": 18.1,
    "RUSH TDS": 0.3,
    "FL": 0,
    "FPTS": 26.1
  },
  {
    "Player": "Jacoby Brissett",
    "Team": "IND",
    "ATT": 5.2,
    "CMP": 19.9,
    "PASS YDS": 200.2,
    "PASS TDS": 1.2,
    "INTS": 1,
    "RUSH YDS": 23.9,
    "RUSH TDS": 0.3,
    "FL": 0.1,
    "FPTS": 14.7
  },
  {
    "Player": "Mike Glennon",
    "Team": "ARI",
    "ATT": 1.7,
    "CMP": 21.4,
    "PASS YDS": 233.5,
    "PASS TDS": 1.5,
    "INTS": 1.2,
    "RUSH YDS": 2.1,
    "RUSH TDS": 0.1,
    "FL": 0,
    "FPTS": 13.5
  },
  {
    "Player": "Brandon Weeden",
    "Team": "HOU",
    "ATT": 2.9,
    "CMP": 23.1,
    "PASS YDS": 231.8,
    "PASS TDS": 1.3,
    "INTS": 1.1,
    "RUSH YDS": 5.9,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 13.1
  },
  {
    "Player": "Blaine Gabbert",
    "Team": "TEN",
    "ATT": 2,
    "CMP": 16.8,
    "PASS YDS": 179.3,
    "PASS TDS": 1,
    "INTS": 1,
    "RUSH YDS": 8.4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 10.4
  },
  {
    "Player": "David Fales",
    "Team": "MIA",
    "ATT": 2.7,
    "CMP": 19.2,
    "PASS YDS": 164.2,
    "PASS TDS": 0.9,
    "INTS": 1,
    "RUSH YDS": 17.9,
    "RUSH TDS": 0.1,
    "FL": 0.2,
    "FPTS": 10.2
  },
  {
    "Player": "Mason Rudolph",
    "Team": "PIT",
    "ATT": 1.3,
    "CMP": 15.3,
    "PASS YDS": 192.3,
    "PASS TDS": 0.9,
    "INTS": 0.9,
    "RUSH YDS": 4.3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 10
  },
  {
    "Player": "Davis Webb",
    "Team": "NYJ",
    "ATT": 2,
    "CMP": 14,
    "PASS YDS": 154,
    "PASS TDS": 1.1,
    "INTS": 0.9,
    "RUSH YDS": 3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 9.1
  },
  {
    "Player": "Chase Daniel",
    "Team": "CHI",
    "ATT": 1.2,
    "CMP": 12.9,
    "PASS YDS": 128.4,
    "PASS TDS": 0.7,
    "INTS": 0.2,
    "RUSH YDS": 2.2,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.7
  },
  {
    "Player": "Colt McCoy",
    "Team": "WAS",
    "ATT": 1.5,
    "CMP": 10.6,
    "PASS YDS": 120.3,
    "PASS TDS": 0.7,
    "INTS": 0.5,
    "RUSH YDS": 4.3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.1
  },
  {
    "Player": "Brett Hundley",
    "Team": "SEA",
    "ATT": 1.7,
    "CMP": 11.3,
    "PASS YDS": 112,
    "PASS TDS": 0.5,
    "INTS": 0.4,
    "RUSH YDS": 9.7,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 6.7
  },
  {
    "Player": "DeShone Kizer",
    "Team": "GB",
    "ATT": 2.5,
    "CMP": 8.6,
    "PASS YDS": 95.3,
    "PASS TDS": 0.5,
    "INTS": 0.4,
    "RUSH YDS": 12.9,
    "RUSH TDS": 0.1,
    "FL": 0.1,
    "FPTS": 6.5
  },
  {
    "Player": "Joshua Dobbs",
    "Team": "PIT",
    "ATT": 0.5,
    "CMP": 10.1,
    "PASS YDS": 98.3,
    "PASS TDS": 0.7,
    "INTS": 0.5,
    "RUSH YDS": 6.8,
    "RUSH TDS": 0.1,
    "FL": 0.1,
    "FPTS": 6.4
  },
  {
    "Player": "Jeff Driskel",
    "Team": "CIN",
    "ATT": 1,
    "CMP": 9.9,
    "PASS YDS": 113.9,
    "PASS TDS": 0.6,
    "INTS": 0.5,
    "RUSH YDS": 3.8,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.4
  },
  {
    "Player": "Brock Osweiler",
    "Team": "MIA",
    "ATT": 0.4,
    "CMP": 9.1,
    "PASS YDS": 121,
    "PASS TDS": 0.6,
    "INTS": 0.6,
    "RUSH YDS": 2.4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.1
  },
  {
    "Player": "Chad Kelly",
    "Team": "DEN",
    "ATT": 1.4,
    "CMP": 8.3,
    "PASS YDS": 116.4,
    "PASS TDS": 0.5,
    "INTS": 0.6,
    "RUSH YDS": 4.1,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.1
  },
  {
    "Player": "C.J. Beathard",
    "Team": "SF",
    "ATT": 1.4,
    "CMP": 9.8,
    "PASS YDS": 101.5,
    "PASS TDS": 0.4,
    "INTS": 0.3,
    "RUSH YDS": 6.4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 5.6
  },
  {
    "Player": "Trevor Siemian",
    "Team": "MIN",
    "ATT": 1.3,
    "CMP": 8.8,
    "PASS YDS": 87.9,
    "PASS TDS": 0.3,
    "INTS": 0.3,
    "RUSH YDS": 7.9,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 5.2
  },
  {
    "Player": "Kyle Lauletta",
    "Team": "NYG",
    "ATT": 0.5,
    "CMP": 7.8,
    "PASS YDS": 95.2,
    "PASS TDS": 0.3,
    "INTS": 0.3,
    "RUSH YDS": 4.8,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 5
  },
  {
    "Player": "AJ McCarron",
    "Team": "OAK",
    "ATT": 1.3,
    "CMP": 8.8,
    "PASS YDS": 100.3,
    "PASS TDS": 0.4,
    "INTS": 0.6,
    "RUSH YDS": 3.3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4.9
  },
  {
    "Player": "Cody Kessler",
    "Team": "JAC",
    "ATT": 0.9,
    "CMP": 7.9,
    "PASS YDS": 87.6,
    "PASS TDS": 0.5,
    "INTS": 0.4,
    "RUSH YDS": 2.6,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4.9
  },
  {
    "Player": "Matt Cassel",
    "Team": "DET",
    "ATT": 1.5,
    "CMP": 8.2,
    "PASS YDS": 89.4,
    "PASS TDS": 0.4,
    "INTS": 0.4,
    "RUSH YDS": 5.3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4.8
  },
  {
    "Player": "Cooper Rush",
    "Team": "DAL",
    "ATT": 1.3,
    "CMP": 6.7,
    "PASS YDS": 69.5,
    "PASS TDS": 0.4,
    "INTS": 0.3,
    "RUSH YDS": 6.5,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4.7
  },
  {
    "Player": "Sean Mannion",
    "Team": "LAR",
    "ATT": 2.4,
    "CMP": 8.2,
    "PASS YDS": 83.7,
    "PASS TDS": 0.3,
    "INTS": 0.4,
    "RUSH YDS": 7.1,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 4.6
  },
  {
    "Player": "Chad Henne",
    "Team": "KC",
    "ATT": 1.1,
    "CMP": 7.8,
    "PASS YDS": 89,
    "PASS TDS": 0.4,
    "INTS": 0.5,
    "RUSH YDS": 2.2,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4.4
  },
  {
    "Player": "Teddy Bridgewater",
    "Team": "NO",
    "ATT": 1.1,
    "CMP": 6.3,
    "PASS YDS": 64.8,
    "PASS TDS": 0.3,
    "INTS": 0.3,
    "RUSH YDS": 7.6,
    "RUSH TDS": 0.1,
    "FL": 0.1,
    "FPTS": 4.4
  },
  {
    "Player": "Brian Hoyer",
    "Team": "NE",
    "ATT": 0.7,
    "CMP": 5.9,
    "PASS YDS": 65.5,
    "PASS TDS": 0.4,
    "INTS": 0.3,
    "RUSH YDS": 6,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 4.4
  },
  {
    "Player": "Geno Smith",
    "Team": "LAC",
    "ATT": 1,
    "CMP": 6.2,
    "PASS YDS": 65.8,
    "PASS TDS": 0.3,
    "INTS": 0.3,
    "RUSH YDS": 3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 3.7
  },
  {
    "Player": "Matt Schaub",
    "Team": "ATL",
    "ATT": 0.6,
    "CMP": 5.7,
    "PASS YDS": 66,
    "PASS TDS": 0.3,
    "INTS": 0.2,
    "RUSH YDS": 1.1,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 3.5
  },
  {
    "Player": "Taylor Heinicke",
    "Team": "CAR",
    "ATT": 0.2,
    "CMP": 3.5,
    "PASS YDS": 45.9,
    "PASS TDS": 0.2,
    "INTS": 0.1,
    "RUSH YDS": 2.2,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 2.7
  },
  {
    "Player": "Robert Griffin",
    "Team": "BAL",
    "ATT": 0.5,
    "CMP": 0.5,
    "PASS YDS": 23.2,
    "PASS TDS": 0.2,
    "INTS": 0.2,
    "RUSH YDS": 6.3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 2.2
  },
  {
    "Player": "Ryan Griffin",
    "Team": "HOU",
    "ATT": 0,
    "CMP": 1.7,
    "PASS YDS": 36.4,
    "PASS TDS": 0.1,
    "INTS": 0.1,
    "RUSH YDS": 1,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 1.9
  },
  {
    "Player": "Tanner Lee",
    "Team": "JAC",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 2,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0.1
  },
  {
    "Player": "Nate Sudfeld",
    "Team": "PHI",
    "ATT": 0,
    "CMP": 0.1,
    "PASS YDS": 0.6,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Drew Stanton",
    "Team": "CLE",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Taysom Hill",
    "Team": "NO",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Joe Webb",
    "Team": "HOU",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Alex Tanney",
    "Team": "NYG",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Jameill Showers",
    "Team": "DAL",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Cardale Jones",
    "Team": "LAC",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Kevin Hogan",
    "Team": "DEN",
    "ATT": 0,
    "CMP": 0,
    "PASS YDS": 0,
    "PASS TDS": 0,
    "INTS": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  }
]