rb_stats =
[
  {
    "Player": "",
    "Team": "",
    "ATT": "",
    "YDS": "",
    "TDS": "",
    "REC": "",
    "REC YDS": "",
    "REC TDS": "",
    "FL": "",
    "FPTS": ""
  },
  {
    "Player": "David Johnson",
    "Team": "ARI",
    "ATT": 282.5,
    "YDS": 1198.9,
    "TDS": 12,
    "REC": 75.5,
    "REC YDS": 742.3,
    "REC TDS": 3.9,
    "FL": 3.1,
    "FPTS": 283.3
  },
  {
    "Player": "Le'Veon Bell",
    "Team": "PIT",
    "ATT": 292.6,
    "YDS": 1340.5,
    "TDS": 9.4,
    "REC": 75.9,
    "REC YDS": 619.9,
    "REC TDS": 2.4,
    "FL": 2.2,
    "FPTS": 262.3
  },
  {
    "Player": "LeSean McCoy",
    "Team": "BUF",
    "ATT": 244.3,
    "YDS": 1188.3,
    "TDS": 9.3,
    "REC": 47.1,
    "REC YDS": 364.9,
    "REC TDS": 1.8,
    "FL": 1,
    "FPTS": 219.7
  },
  {
    "Player": "Devonta Freeman",
    "Team": "ATL",
    "ATT": 219.3,
    "YDS": 968.2,
    "TDS": 8.9,
    "REC": 55.4,
    "REC YDS": 484.8,
    "REC TDS": 2.7,
    "FL": 1.8,
    "FPTS": 211
  },
  {
    "Player": "Melvin Gordon",
    "Team": "LAC",
    "ATT": 273,
    "YDS": 1095.5,
    "TDS": 8.1,
    "REC": 46.6,
    "REC YDS": 399.9,
    "REC TDS": 1.9,
    "FL": 3.8,
    "FPTS": 202
  },
  {
    "Player": "Jordan Howard",
    "Team": "CHI",
    "ATT": 266,
    "YDS": 1234,
    "TDS": 7,
    "REC": 35.7,
    "REC YDS": 311.4,
    "REC TDS": 1.4,
    "FL": 1.6,
    "FPTS": 201.9
  },
  {
    "Player": "Jay Ajayi",
    "Team": "MIA",
    "ATT": 264.7,
    "YDS": 1191.2,
    "TDS": 8.3,
    "REC": 35.2,
    "REC YDS": 248.2,
    "REC TDS": 1.3,
    "FL": 1.3,
    "FPTS": 199.2
  },
  {
    "Player": "DeMarco Murray",
    "Team": "TEN",
    "ATT": 248.4,
    "YDS": 1073.9,
    "TDS": 7.5,
    "REC": 44.5,
    "REC YDS": 321.1,
    "REC TDS": 2.1,
    "FL": 1.8,
    "FPTS": 193.4
  },
  {
    "Player": "Todd Gurley",
    "Team": "LAR",
    "ATT": 275.6,
    "YDS": 1044.4,
    "TDS": 7.9,
    "REC": 38.6,
    "REC YDS": 296.5,
    "REC TDS": 1,
    "FL": 1.4,
    "FPTS": 184.8
  },
  {
    "Player": "Lamar Miller",
    "Team": "HOU",
    "ATT": 261.9,
    "YDS": 1063.6,
    "TDS": 6.5,
    "REC": 36,
    "REC YDS": 262.4,
    "REC TDS": 1.4,
    "FL": 1.6,
    "FPTS": 176.4
  },
  {
    "Player": "Leonard Fournette",
    "Team": "JAC",
    "ATT": 239,
    "YDS": 1042.2,
    "TDS": 7.1,
    "REC": 30.4,
    "REC YDS": 228,
    "REC TDS": 1.2,
    "FL": 1.8,
    "FPTS": 173.4
  },
  {
    "Player": "Ezekiel Elliott",
    "Team": "DAL",
    "ATT": 199.7,
    "YDS": 961.2,
    "TDS": 7.1,
    "REC": 25.7,
    "REC YDS": 243.4,
    "REC TDS": 1,
    "FL": 0.9,
    "FPTS": 167.1
  },
  {
    "Player": "Isaiah Crowell",
    "Team": "CLE",
    "ATT": 215.2,
    "YDS": 921.7,
    "TDS": 6.1,
    "REC": 37.1,
    "REC YDS": 296.5,
    "REC TDS": 0.6,
    "FL": 1.6,
    "FPTS": 159.2
  },
  {
    "Player": "Marshawn Lynch",
    "Team": "OAK",
    "ATT": 196.1,
    "YDS": 821.5,
    "TDS": 7.9,
    "REC": 32.1,
    "REC YDS": 239.8,
    "REC TDS": 1.1,
    "FL": 1.3,
    "FPTS": 157.1
  },
  {
    "Player": "Spencer Ware",
    "Team": "KC",
    "ATT": 199.8,
    "YDS": 850.4,
    "TDS": 6.1,
    "REC": 32.3,
    "REC YDS": 297.7,
    "REC TDS": 1.3,
    "FL": 4.1,
    "FPTS": 150.9
  },
  {
    "Player": "Dalvin Cook",
    "Team": "MIN",
    "ATT": 183.9,
    "YDS": 773.6,
    "TDS": 6,
    "REC": 37.5,
    "REC YDS": 295.1,
    "REC TDS": 1.5,
    "FL": 1.6,
    "FPTS": 149.1
  },
  {
    "Player": "Ty Montgomery",
    "Team": "GB",
    "ATT": 154.5,
    "YDS": 728.4,
    "TDS": 5.1,
    "REC": 44.9,
    "REC YDS": 362.2,
    "REC TDS": 1.9,
    "FL": 1.5,
    "FPTS": 148.1
  },
  {
    "Player": "Christian McCaffrey",
    "Team": "CAR",
    "ATT": 153.1,
    "YDS": 682.6,
    "TDS": 4.4,
    "REC": 49.6,
    "REC YDS": 429.7,
    "REC TDS": 2.3,
    "FL": 1.7,
    "FPTS": 147.7
  },
  {
    "Player": "Mark Ingram",
    "Team": "NO",
    "ATT": 168.4,
    "YDS": 752.6,
    "TDS": 5.4,
    "REC": 42.2,
    "REC YDS": 318,
    "REC TDS": 2.2,
    "FL": 2.5,
    "FPTS": 147.4
  },
  {
    "Player": "Joe Mixon",
    "Team": "CIN",
    "ATT": 184.3,
    "YDS": 767.9,
    "TDS": 6.2,
    "REC": 34.6,
    "REC YDS": 274.1,
    "REC TDS": 1,
    "FL": 1.5,
    "FPTS": 144.2
  },
  {
    "Player": "Bilal Powell",
    "Team": "NYJ",
    "ATT": 156.2,
    "YDS": 714,
    "TDS": 4.1,
    "REC": 51.9,
    "REC YDS": 377.8,
    "REC TDS": 1.8,
    "FL": 1.2,
    "FPTS": 142.2
  },
  {
    "Player": "Carlos Hyde",
    "Team": "SF",
    "ATT": 213.4,
    "YDS": 907.5,
    "TDS": 5.8,
    "REC": 26.5,
    "REC YDS": 180.8,
    "REC TDS": 1.3,
    "FL": 5.5,
    "FPTS": 140.3
  },
  {
    "Player": "Frank Gore",
    "Team": "IND",
    "ATT": 206.9,
    "YDS": 799.5,
    "TDS": 4.8,
    "REC": 29.8,
    "REC YDS": 231.3,
    "REC TDS": 1.6,
    "FL": 2,
    "FPTS": 137.8
  },
  {
    "Player": "Tevin Coleman",
    "Team": "ATL",
    "ATT": 129.3,
    "YDS": 566,
    "TDS": 5.1,
    "REC": 35.6,
    "REC YDS": 364.5,
    "REC TDS": 2.6,
    "FL": 1.3,
    "FPTS": 136.3
  },
  {
    "Player": "Paul Perkins",
    "Team": "NYG",
    "ATT": 205.3,
    "YDS": 835.7,
    "TDS": 4.2,
    "REC": 25.8,
    "REC YDS": 222.4,
    "REC TDS": 1,
    "FL": 1.5,
    "FPTS": 133.8
  },
  {
    "Player": "Terrance West",
    "Team": "BAL",
    "ATT": 188.1,
    "YDS": 753.3,
    "TDS": 5.1,
    "REC": 32.3,
    "REC YDS": 228.5,
    "REC TDS": 1.1,
    "FL": 1,
    "FPTS": 133
  },
  {
    "Player": "Mike Gillislee",
    "Team": "NE",
    "ATT": 164.7,
    "YDS": 772.3,
    "TDS": 7.5,
    "REC": 13.8,
    "REC YDS": 106.6,
    "REC TDS": 0.4,
    "FL": 1.4,
    "FPTS": 132.7
  },
  {
    "Player": "Ameer Abdullah",
    "Team": "DET",
    "ATT": 166.2,
    "YDS": 699.6,
    "TDS": 4.2,
    "REC": 33,
    "REC YDS": 279.8,
    "REC TDS": 2,
    "FL": 1.9,
    "FPTS": 131.3
  },
  {
    "Player": "C.J. Anderson",
    "Team": "DEN",
    "ATT": 175.9,
    "YDS": 746.2,
    "TDS": 4.8,
    "REC": 28.6,
    "REC YDS": 221.9,
    "REC TDS": 1,
    "FL": 1.8,
    "FPTS": 127.8
  },
  {
    "Player": "Eddie Lacy",
    "Team": "SEA",
    "ATT": 176.2,
    "YDS": 774.8,
    "TDS": 5.1,
    "REC": 19.4,
    "REC YDS": 155.7,
    "REC TDS": 0.9,
    "FL": 1.1,
    "FPTS": 126.9
  },
  {
    "Player": "Rob Kelley",
    "Team": "WAS",
    "ATT": 188.6,
    "YDS": 783.3,
    "TDS": 5.9,
    "REC": 16.3,
    "REC YDS": 124.6,
    "REC TDS": 0.4,
    "FL": 1.5,
    "FPTS": 125.2
  },
  {
    "Player": "Danny Woodhead",
    "Team": "BAL",
    "ATT": 89.7,
    "YDS": 379,
    "TDS": 2.6,
    "REC": 61,
    "REC YDS": 491.8,
    "REC TDS": 2.9,
    "FL": 1,
    "FPTS": 118.1
  },
  {
    "Player": "Matt Forte",
    "Team": "NYJ",
    "ATT": 149.6,
    "YDS": 611,
    "TDS": 3.7,
    "REC": 31.6,
    "REC YDS": 258,
    "REC TDS": 1.4,
    "FL": 1.7,
    "FPTS": 113.8
  },
  {
    "Player": "Theo Riddick",
    "Team": "DET",
    "ATT": 83.9,
    "YDS": 325.9,
    "TDS": 2,
    "REC": 62.5,
    "REC YDS": 496.7,
    "REC TDS": 3.4,
    "FL": 0.9,
    "FPTS": 112.7
  },
  {
    "Player": "Doug Martin",
    "Team": "TB",
    "ATT": 176.4,
    "YDS": 697.3,
    "TDS": 4.6,
    "REC": 20.3,
    "REC YDS": 161.4,
    "REC TDS": 0.8,
    "FL": 3.4,
    "FPTS": 111.3
  },
  {
    "Player": "Jonathan Stewart",
    "Team": "CAR",
    "ATT": 176.3,
    "YDS": 720.8,
    "TDS": 5.4,
    "REC": 11.8,
    "REC YDS": 90,
    "REC TDS": 0.5,
    "FL": 3.5,
    "FPTS": 109.6
  },
  {
    "Player": "LeGarrette Blount",
    "Team": "PHI",
    "ATT": 175.5,
    "YDS": 707.9,
    "TDS": 5.9,
    "REC": 9.5,
    "REC YDS": 60.7,
    "REC TDS": 0.2,
    "FL": 1.9,
    "FPTS": 109.5
  },
  {
    "Player": "Duke Johnson",
    "Team": "CLE",
    "ATT": 84.5,
    "YDS": 355.9,
    "TDS": 1.9,
    "REC": 57.4,
    "REC YDS": 496.8,
    "REC TDS": 1.7,
    "FL": 1.4,
    "FPTS": 104.2
  },
  {
    "Player": "Adrian Peterson",
    "Team": "NO",
    "ATT": 147.6,
    "YDS": 617.6,
    "TDS": 5.6,
    "REC": 22.2,
    "REC YDS": 147.8,
    "REC TDS": 0.5,
    "FL": 4.9,
    "FPTS": 103.5
  },
  {
    "Player": "Derrick Henry",
    "Team": "TEN",
    "ATT": 138.8,
    "YDS": 598.5,
    "TDS": 4.3,
    "REC": 16.1,
    "REC YDS": 146.5,
    "REC TDS": 0.8,
    "FL": 1.2,
    "FPTS": 102.4
  },
  {
    "Player": "Kareem Hunt",
    "Team": "KC",
    "ATT": 118,
    "YDS": 493.6,
    "TDS": 3.8,
    "REC": 29.1,
    "REC YDS": 227.9,
    "REC TDS": 0.9,
    "FL": 1.8,
    "FPTS": 97
  },
  {
    "Player": "Darren Sproles",
    "Team": "PHI",
    "ATT": 83.9,
    "YDS": 372.2,
    "TDS": 2.2,
    "REC": 48.8,
    "REC YDS": 378.3,
    "REC TDS": 1.8,
    "FL": 1.2,
    "FPTS": 96.6
  },
  {
    "Player": "Darren McFadden",
    "Team": "DAL",
    "ATT": 125.4,
    "YDS": 529.7,
    "TDS": 4.2,
    "REC": 20.9,
    "REC YDS": 163.5,
    "REC TDS": 0.3,
    "FL": 2.8,
    "FPTS": 90.9
  },
  {
    "Player": "Giovani Bernard",
    "Team": "CIN",
    "ATT": 102.9,
    "YDS": 420.9,
    "TDS": 2.3,
    "REC": 35.2,
    "REC YDS": 300.5,
    "REC TDS": 1.4,
    "FL": 1.9,
    "FPTS": 90.4
  },
  {
    "Player": "James White",
    "Team": "NE",
    "ATT": 51.1,
    "YDS": 212,
    "TDS": 1.5,
    "REC": 49,
    "REC YDS": 418.4,
    "REC TDS": 3.4,
    "FL": 1.4,
    "FPTS": 89.2
  },
  {
    "Player": "Thomas Rawls",
    "Team": "SEA",
    "ATT": 118.3,
    "YDS": 495.3,
    "TDS": 4.2,
    "REC": 13.9,
    "REC YDS": 107,
    "REC TDS": 0.3,
    "FL": 0.9,
    "FPTS": 85.3
  },
  {
    "Player": "Chris Thompson",
    "Team": "WAS",
    "ATT": 57,
    "YDS": 271,
    "TDS": 1.8,
    "REC": 47.7,
    "REC YDS": 362.5,
    "REC TDS": 2,
    "FL": 1.5,
    "FPTS": 83.1
  },
  {
    "Player": "C.J. Prosise",
    "Team": "SEA",
    "ATT": 58.8,
    "YDS": 264.4,
    "TDS": 1.9,
    "REC": 39.2,
    "REC YDS": 379.1,
    "REC TDS": 1.3,
    "FL": 1,
    "FPTS": 81.8
  },
  {
    "Player": "Jamaal Charles",
    "Team": "DEN",
    "ATT": 101.5,
    "YDS": 450.3,
    "TDS": 3.2,
    "REC": 26.4,
    "REC YDS": 209.9,
    "REC TDS": 1,
    "FL": 4.8,
    "FPTS": 81.8
  },
  {
    "Player": "Jamaal Williams",
    "Team": "GB",
    "ATT": 115.2,
    "YDS": 491.4,
    "TDS": 3.8,
    "REC": 11.4,
    "REC YDS": 84,
    "REC TDS": 0.3,
    "FL": 1.6,
    "FPTS": 78.6
  },
  {
    "Player": "Jeremy Hill",
    "Team": "CIN",
    "ATT": 115.5,
    "YDS": 450.9,
    "TDS": 3.7,
    "REC": 11.5,
    "REC YDS": 86,
    "REC TDS": 0.2,
    "FL": 1.3,
    "FPTS": 74.4
  },
  {
    "Player": "Latavius Murray",
    "Team": "MIN",
    "ATT": 111.5,
    "YDS": 445.1,
    "TDS": 3.5,
    "REC": 16.7,
    "REC YDS": 115.9,
    "REC TDS": 0.2,
    "FL": 2.4,
    "FPTS": 73.6
  },
  {
    "Player": "Rex Burkhead",
    "Team": "NE",
    "ATT": 92.1,
    "YDS": 389.3,
    "TDS": 3.1,
    "REC": 16.3,
    "REC YDS": 133.9,
    "REC TDS": 0.9,
    "FL": 1.6,
    "FPTS": 73.4
  },
  {
    "Player": "Shane Vereen",
    "Team": "NYG",
    "ATT": 66.7,
    "YDS": 288,
    "TDS": 1.5,
    "REC": 38.6,
    "REC YDS": 307.6,
    "REC TDS": 1.9,
    "FL": 3.5,
    "FPTS": 72.9
  },
  {
    "Player": "Jacquizz Rodgers",
    "Team": "TB",
    "ATT": 107.5,
    "YDS": 454.9,
    "TDS": 2.5,
    "REC": 16.6,
    "REC YDS": 118.9,
    "REC TDS": 0.2,
    "FL": 1.3,
    "FPTS": 71.2
  },
  {
    "Player": "Charles Sims",
    "Team": "TB",
    "ATT": 72.9,
    "YDS": 284.2,
    "TDS": 1.4,
    "REC": 33,
    "REC YDS": 290.2,
    "REC TDS": 1.7,
    "FL": 2.6,
    "FPTS": 71.1
  },
  {
    "Player": "Samaje Perine",
    "Team": "WAS",
    "ATT": 104.1,
    "YDS": 422.1,
    "TDS": 3.2,
    "REC": 13.4,
    "REC YDS": 106.4,
    "REC TDS": 0.2,
    "FL": 1.8,
    "FPTS": 69.9
  },
  {
    "Player": "DeAndre Washington",
    "Team": "OAK",
    "ATT": 90.8,
    "YDS": 421.1,
    "TDS": 2.3,
    "REC": 18.9,
    "REC YDS": 136.6,
    "REC TDS": 0.5,
    "FL": 2.1,
    "FPTS": 68.6
  },
  {
    "Player": "Robert Turbin",
    "Team": "IND",
    "ATT": 76.7,
    "YDS": 296.5,
    "TDS": 2.8,
    "REC": 23.8,
    "REC YDS": 172.1,
    "REC TDS": 1.2,
    "FL": 1.1,
    "FPTS": 68.5
  },
  {
    "Player": "Dion Lewis",
    "Team": "NE",
    "ATT": 74.8,
    "YDS": 322.6,
    "TDS": 2.2,
    "REC": 22.7,
    "REC YDS": 170.5,
    "REC TDS": 0.9,
    "FL": 3.7,
    "FPTS": 60.2
  },
  {
    "Player": "Jalen Richard",
    "Team": "OAK",
    "ATT": 60,
    "YDS": 291.4,
    "TDS": 1.5,
    "REC": 23.4,
    "REC YDS": 173.5,
    "REC TDS": 0.9,
    "FL": 1.3,
    "FPTS": 58.4
  },
  {
    "Player": "Tim Hightower",
    "Team": "SF",
    "ATT": 84.3,
    "YDS": 343.9,
    "TDS": 2.2,
    "REC": 14.1,
    "REC YDS": 114.8,
    "REC TDS": 0.2,
    "FL": 1.6,
    "FPTS": 57.3
  },
  {
    "Player": "Jonathan Williams",
    "Team": "BUF",
    "ATT": 92.5,
    "YDS": 387.2,
    "TDS": 3.1,
    "REC": 10.7,
    "REC YDS": 72.9,
    "REC TDS": 0.2,
    "FL": 4.8,
    "FPTS": 56.4
  },
  {
    "Player": "T.J. Yeldon",
    "Team": "JAC",
    "ATT": 65.2,
    "YDS": 243.7,
    "TDS": 1.1,
    "REC": 32.1,
    "REC YDS": 226.1,
    "REC TDS": 0.9,
    "FL": 1.5,
    "FPTS": 55.8
  },
  {
    "Player": "Alvin Kamara",
    "Team": "NO",
    "ATT": 44.5,
    "YDS": 189.8,
    "TDS": 1.6,
    "REC": 28.6,
    "REC YDS": 229.8,
    "REC TDS": 0.9,
    "FL": 1.5,
    "FPTS": 53.9
  },
  {
    "Player": "D'Onta Foreman",
    "Team": "HOU",
    "ATT": 80.5,
    "YDS": 320.1,
    "TDS": 2.3,
    "REC": 13.5,
    "REC YDS": 95.6,
    "REC TDS": 0.1,
    "FL": 1.3,
    "FPTS": 53.8
  },
  {
    "Player": "Jerick McKinnon",
    "Team": "MIN",
    "ATT": 58.7,
    "YDS": 229.4,
    "TDS": 1,
    "REC": 27,
    "REC YDS": 186.5,
    "REC TDS": 1.1,
    "FL": 1.3,
    "FPTS": 51.2
  },
  {
    "Player": "Joe Williams",
    "Team": "SF",
    "ATT": 71.2,
    "YDS": 297.6,
    "TDS": 1.8,
    "REC": 14.6,
    "REC YDS": 109.7,
    "REC TDS": 0.4,
    "FL": 1.9,
    "FPTS": 50.5
  },
  {
    "Player": "Marlon Mack",
    "Team": "IND",
    "ATT": 57.1,
    "YDS": 229.2,
    "TDS": 1.6,
    "REC": 18.3,
    "REC YDS": 142.1,
    "REC TDS": 0.6,
    "FL": 1.3,
    "FPTS": 47.7
  },
  {
    "Player": "Donnel Pumphrey",
    "Team": "PHI",
    "ATT": 63.9,
    "YDS": 256.9,
    "TDS": 1.2,
    "REC": 17.3,
    "REC YDS": 129.3,
    "REC TDS": 0.3,
    "FL": 1.4,
    "FPTS": 44.7
  },
  {
    "Player": "Devontae Booker",
    "Team": "DEN",
    "ATT": 72.1,
    "YDS": 278.8,
    "TDS": 1.4,
    "REC": 16.1,
    "REC YDS": 128,
    "REC TDS": 0.6,
    "FL": 3.8,
    "FPTS": 44.5
  },
  {
    "Player": "Damien Williams",
    "Team": "MIA",
    "ATT": 42.7,
    "YDS": 157,
    "TDS": 1.2,
    "REC": 18.6,
    "REC YDS": 161.5,
    "REC TDS": 1.5,
    "FL": 1.7,
    "FPTS": 44.3
  },
  {
    "Player": "Alfred Morris",
    "Team": "DAL",
    "ATT": 67.1,
    "YDS": 281,
    "TDS": 1.7,
    "REC": 6.3,
    "REC YDS": 40.3,
    "REC TDS": 0.2,
    "FL": 0.6,
    "FPTS": 42.3
  },
  {
    "Player": "James Conner",
    "Team": "PIT",
    "ATT": 55.6,
    "YDS": 226.5,
    "TDS": 2.1,
    "REC": 9.8,
    "REC YDS": 74.7,
    "REC TDS": 0.2,
    "FL": 0.9,
    "FPTS": 41.6
  },
  {
    "Player": "Chris Johnson",
    "Team": "ARI",
    "ATT": 64.1,
    "YDS": 263.4,
    "TDS": 1.6,
    "REC": 5.1,
    "REC YDS": 39.9,
    "REC TDS": 0.2,
    "FL": 1.5,
    "FPTS": 37.8
  },
  {
    "Player": "Tarik Cohen",
    "Team": "CHI",
    "ATT": 45.4,
    "YDS": 199.1,
    "TDS": 1.2,
    "REC": 15.7,
    "REC YDS": 127.1,
    "REC TDS": 0.3,
    "FL": 1.9,
    "FPTS": 37.8
  },
  {
    "Player": "Zach Zenner",
    "Team": "DET",
    "ATT": 46.4,
    "YDS": 175.3,
    "TDS": 1.7,
    "REC": 11.9,
    "REC YDS": 101.2,
    "REC TDS": 0.1,
    "FL": 0.3,
    "FPTS": 37.7
  },
  {
    "Player": "Marcel Reece",
    "Team": "SEA",
    "ATT": 10,
    "YDS": 20,
    "TDS": 0.1,
    "REC": 26,
    "REC YDS": 278,
    "REC TDS": 1.1,
    "FL": 0,
    "FPTS": 37
  },
  {
    "Player": "Wendell Smallwood",
    "Team": "PHI",
    "ATT": 61.9,
    "YDS": 254.3,
    "TDS": 1.3,
    "REC": 8.8,
    "REC YDS": 65.2,
    "REC TDS": 0.1,
    "FL": 2.4,
    "FPTS": 35.6
  },
  {
    "Player": "Kyle Juszczyk",
    "Team": "SF",
    "ATT": 6.3,
    "YDS": 25.3,
    "TDS": 0.3,
    "REC": 27.5,
    "REC YDS": 217.7,
    "REC TDS": 1.5,
    "FL": 0,
    "FPTS": 34.9
  },
  {
    "Player": "Branden Oliver",
    "Team": "LAC",
    "ATT": 50.6,
    "YDS": 191.9,
    "TDS": 1,
    "REC": 12.8,
    "REC YDS": 104.4,
    "REC TDS": 0.4,
    "FL": 1.9,
    "FPTS": 34
  },
  {
    "Player": "Orleans Darkwa",
    "Team": "NYG",
    "ATT": 45.1,
    "YDS": 168.9,
    "TDS": 1.6,
    "REC": 10.7,
    "REC YDS": 76,
    "REC TDS": 0.3,
    "FL": 1.5,
    "FPTS": 32.7
  },
  {
    "Player": "Elijah McGuire",
    "Team": "NYJ",
    "ATT": 42.9,
    "YDS": 176.7,
    "TDS": 1,
    "REC": 12.2,
    "REC YDS": 94.9,
    "REC TDS": 0.2,
    "FL": 1.5,
    "FPTS": 31.3
  },
  {
    "Player": "Chris Ivory",
    "Team": "JAC",
    "ATT": 55.9,
    "YDS": 218,
    "TDS": 1.7,
    "REC": 10.2,
    "REC YDS": 78.9,
    "REC TDS": 0.1,
    "FL": 4.8,
    "FPTS": 30.5
  },
  {
    "Player": "Kenyan Drake",
    "Team": "MIA",
    "ATT": 41.7,
    "YDS": 178.1,
    "TDS": 1,
    "REC": 9.8,
    "REC YDS": 71.7,
    "REC TDS": 0.2,
    "FL": 1.3,
    "FPTS": 29.5
  },
  {
    "Player": "Andre Ellington",
    "Team": "ARI",
    "ATT": 24.8,
    "YDS": 101.5,
    "TDS": 0.7,
    "REC": 15,
    "REC YDS": 122.6,
    "REC TDS": 0.4,
    "FL": 0.1,
    "FPTS": 28.5
  },
  {
    "Player": "Wayne Gallman",
    "Team": "NYG",
    "ATT": 46.8,
    "YDS": 180.1,
    "TDS": 1.1,
    "REC": 8.9,
    "REC YDS": 68.5,
    "REC TDS": 0.1,
    "FL": 1.8,
    "FPTS": 28.4
  },
  {
    "Player": "Jeremy Langford",
    "Team": "CHI",
    "ATT": 37.8,
    "YDS": 150.5,
    "TDS": 0.9,
    "REC": 8.6,
    "REC YDS": 68.5,
    "REC TDS": 0.3,
    "FL": 0.3,
    "FPTS": 28.3
  },
  {
    "Player": "Mike Tolbert",
    "Team": "BUF",
    "ATT": 32.9,
    "YDS": 129.8,
    "TDS": 0.9,
    "REC": 9.5,
    "REC YDS": 69,
    "REC TDS": 0.5,
    "FL": 0.3,
    "FPTS": 27.9
  },
  {
    "Player": "Alfred Blue",
    "Team": "HOU",
    "ATT": 45.8,
    "YDS": 181.5,
    "TDS": 0.9,
    "REC": 9.8,
    "REC YDS": 64.6,
    "REC TDS": 0.2,
    "FL": 1.7,
    "FPTS": 27.7
  },
  {
    "Player": "Lance Dunbar",
    "Team": "LAR",
    "ATT": 25.4,
    "YDS": 101.7,
    "TDS": 0.7,
    "REC": 13.2,
    "REC YDS": 107,
    "REC TDS": 0.5,
    "FL": 0.7,
    "FPTS": 26.2
  },
  {
    "Player": "Aaron Ripkowski",
    "Team": "GB",
    "ATT": 22,
    "YDS": 105.7,
    "TDS": 1.6,
    "REC": 7.7,
    "REC YDS": 56.7,
    "REC TDS": 0.5,
    "FL": 1.7,
    "FPTS": 25.6
  },
  {
    "Player": "Aaron Jones",
    "Team": "GB",
    "ATT": 33.1,
    "YDS": 133.8,
    "TDS": 0.9,
    "REC": 6.2,
    "REC YDS": 49.3,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 24.4
  },
  {
    "Player": "Elijah Hood",
    "Team": "OAK",
    "ATT": 34.6,
    "YDS": 144.3,
    "TDS": 1.3,
    "REC": 5.2,
    "REC YDS": 40.7,
    "REC TDS": 0.2,
    "FL": 1.5,
    "FPTS": 24.2
  },
  {
    "Player": "John Kuhn",
    "Team": "NO",
    "ATT": 9.9,
    "YDS": 29.3,
    "TDS": 1.7,
    "REC": 10.4,
    "REC YDS": 62.4,
    "REC TDS": 0.3,
    "FL": 0,
    "FPTS": 21.4
  },
  {
    "Player": "Kerwynn Williams",
    "Team": "ARI",
    "ATT": 20,
    "YDS": 92.9,
    "TDS": 0.7,
    "REC": 5.9,
    "REC YDS": 46,
    "REC TDS": 0.1,
    "FL": 0.2,
    "FPTS": 18.3
  },
  {
    "Player": "Brian Hill",
    "Team": "ATL",
    "ATT": 24.6,
    "YDS": 98.6,
    "TDS": 0.9,
    "REC": 3.1,
    "REC YDS": 23.7,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 17.7
  },
  {
    "Player": "Charcandrick West",
    "Team": "KC",
    "ATT": 27.9,
    "YDS": 103.7,
    "TDS": 0.7,
    "REC": 6.9,
    "REC YDS": 52.9,
    "REC TDS": 0.2,
    "FL": 1.8,
    "FPTS": 17.4
  },
  {
    "Player": "Benny Cunningham",
    "Team": "CHI",
    "ATT": 19.1,
    "YDS": 81.5,
    "TDS": 0.4,
    "REC": 11.5,
    "REC YDS": 88.6,
    "REC TDS": 0.2,
    "FL": 1.6,
    "FPTS": 16.9
  },
  {
    "Player": "Malcolm Brown",
    "Team": "LAR",
    "ATT": 24.8,
    "YDS": 92.4,
    "TDS": 0.5,
    "REC": 7.5,
    "REC YDS": 54.7,
    "REC TDS": 0.1,
    "FL": 0.8,
    "FPTS": 16.7
  },
  {
    "Player": "Javorius Allen",
    "Team": "BAL",
    "ATT": 25,
    "YDS": 95,
    "TDS": 0.5,
    "REC": 5.3,
    "REC YDS": 37.6,
    "REC TDS": 0.1,
    "FL": 0.2,
    "FPTS": 16.5
  },
  {
    "Player": "Andre Williams",
    "Team": "LAC",
    "ATT": 26.6,
    "YDS": 98.5,
    "TDS": 0.6,
    "REC": 2,
    "REC YDS": 17,
    "REC TDS": 0.1,
    "FL": 0,
    "FPTS": 15.6
  },
  {
    "Player": "De'Angelo Henderson",
    "Team": "DEN",
    "ATT": 21.5,
    "YDS": 81.2,
    "TDS": 0.4,
    "REC": 4.8,
    "REC YDS": 49.4,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 15
  },
  {
    "Player": "Matt Asiata",
    "Team": "DET",
    "ATT": 15.6,
    "YDS": 57.9,
    "TDS": 0.8,
    "REC": 5.8,
    "REC YDS": 45.9,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 15
  },
  {
    "Player": "Cameron Artis-Payne",
    "Team": "CAR",
    "ATT": 18.8,
    "YDS": 74.9,
    "TDS": 0.9,
    "REC": 1.4,
    "REC YDS": 15.8,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 13.9
  },
  {
    "Player": "Shaun Draughn",
    "Team": "NYG",
    "ATT": 19.6,
    "YDS": 73.8,
    "TDS": 0.4,
    "REC": 5.2,
    "REC YDS": 40.2,
    "REC TDS": 0.1,
    "FL": 0.2,
    "FPTS": 13.8
  },
  {
    "Player": "Jamize Olawale",
    "Team": "OAK",
    "ATT": 10.3,
    "YDS": 40,
    "TDS": 0.3,
    "REC": 6.1,
    "REC YDS": 59.7,
    "REC TDS": 0.3,
    "FL": 0,
    "FPTS": 13.7
  },
  {
    "Player": "Kenjon Barner",
    "Team": "LAC",
    "ATT": 23.1,
    "YDS": 86.9,
    "TDS": 0.6,
    "REC": 5.7,
    "REC YDS": 43,
    "REC TDS": 0.2,
    "FL": 2.1,
    "FPTS": 13.5
  },
  {
    "Player": "Kenneth Farrow",
    "Team": "LAC",
    "ATT": 19.9,
    "YDS": 70.7,
    "TDS": 0.7,
    "REC": 4.8,
    "REC YDS": 32.8,
    "REC TDS": 0,
    "FL": 0.4,
    "FPTS": 13.5
  },
  {
    "Player": "Ka'Deem Carey",
    "Team": "CHI",
    "ATT": 22.2,
    "YDS": 84.9,
    "TDS": 0.4,
    "REC": 2.9,
    "REC YDS": 25.3,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 13.1
  },
  {
    "Player": "Andy Janovich",
    "Team": "DEN",
    "ATT": 5.3,
    "YDS": 27.2,
    "TDS": 0.6,
    "REC": 7.2,
    "REC YDS": 57,
    "REC TDS": 0.1,
    "FL": 0,
    "FPTS": 13
  },
  {
    "Player": "Dwayne Washington",
    "Team": "DET",
    "ATT": 19.3,
    "YDS": 71.2,
    "TDS": 0.4,
    "REC": 3.6,
    "REC YDS": 23.8,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 11.6
  },
  {
    "Player": "Travaris Cadet",
    "Team": "NO",
    "ATT": 3.9,
    "YDS": 15.8,
    "TDS": 0,
    "REC": 12.1,
    "REC YDS": 90.5,
    "REC TDS": 0.2,
    "FL": 0.2,
    "FPTS": 11.4
  },
  {
    "Player": "Jeremy McNichols",
    "Team": "TB",
    "ATT": 16.3,
    "YDS": 63.7,
    "TDS": 0.2,
    "REC": 5.1,
    "REC YDS": 38.1,
    "REC TDS": 0.1,
    "FL": 0.3,
    "FPTS": 11.4
  },
  {
    "Player": "Fitzgerald Toussaint",
    "Team": "PIT",
    "ATT": 16.4,
    "YDS": 62.1,
    "TDS": 0.1,
    "REC": 4.6,
    "REC YDS": 40.2,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 10.9
  },
  {
    "Player": "Brandon Wilds",
    "Team": "CLE",
    "ATT": 15.2,
    "YDS": 56.4,
    "TDS": 0.4,
    "REC": 3.2,
    "REC YDS": 27.7,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 10.7
  },
  {
    "Player": "Lorenzo Taliaferro",
    "Team": "BAL",
    "ATT": 13.5,
    "YDS": 49.8,
    "TDS": 0.4,
    "REC": 4,
    "REC YDS": 25.5,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 10.2
  },
  {
    "Player": "Fozzy Whittaker",
    "Team": "CAR",
    "ATT": 12.6,
    "YDS": 53.7,
    "TDS": 0.2,
    "REC": 3.8,
    "REC YDS": 31,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 9.6
  },
  {
    "Player": "Terron Ward",
    "Team": "ATL",
    "ATT": 15.2,
    "YDS": 64.9,
    "TDS": 0.1,
    "REC": 2.9,
    "REC YDS": 25.3,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 9.6
  },
  {
    "Player": "Tyler Ervin",
    "Team": "HOU",
    "ATT": 5.4,
    "YDS": 20.8,
    "TDS": 0.1,
    "REC": 6.7,
    "REC YDS": 55.1,
    "REC TDS": 0.2,
    "FL": 0,
    "FPTS": 9.5
  },
  {
    "Player": "Alex Collins",
    "Team": "SEA",
    "ATT": 13.3,
    "YDS": 53.3,
    "TDS": 0.3,
    "REC": 2.7,
    "REC YDS": 24.4,
    "REC TDS": 0,
    "FL": 0.5,
    "FPTS": 8.3
  },
  {
    "Player": "Devante Mays",
    "Team": "GB",
    "ATT": 10,
    "YDS": 41,
    "TDS": 0.3,
    "REC": 2,
    "REC YDS": 16,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 7.9
  },
  {
    "Player": "Patrick DiMarco",
    "Team": "BUF",
    "ATT": 5.4,
    "YDS": 19.9,
    "TDS": 0.1,
    "REC": 5.2,
    "REC YDS": 39.3,
    "REC TDS": 0.2,
    "FL": 0,
    "FPTS": 7.8
  },
  {
    "Player": "Darrel Young",
    "Team": "CAR",
    "ATT": 4.4,
    "YDS": 18.6,
    "TDS": 0.2,
    "REC": 3.9,
    "REC YDS": 33.6,
    "REC TDS": 0.2,
    "FL": 0,
    "FPTS": 7.6
  },
  {
    "Player": "Corey Grant",
    "Team": "JAC",
    "ATT": 10.5,
    "YDS": 43.3,
    "TDS": 0.3,
    "REC": 1.2,
    "REC YDS": 12.3,
    "REC TDS": 0.2,
    "FL": 0.2,
    "FPTS": 7.6
  },
  {
    "Player": "Mack Brown",
    "Team": "WAS",
    "ATT": 9,
    "YDS": 39,
    "TDS": 0.4,
    "REC": 2.2,
    "REC YDS": 14.4,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 7.4
  },
  {
    "Player": "Chris Carson",
    "Team": "SEA",
    "ATT": 10,
    "YDS": 36,
    "TDS": 0.3,
    "REC": 2,
    "REC YDS": 15,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 7.3
  },
  {
    "Player": "Peyton Barber",
    "Team": "TB",
    "ATT": 10.7,
    "YDS": 45,
    "TDS": 0.3,
    "REC": 2,
    "REC YDS": 14.3,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 7.2
  },
  {
    "Player": "Kapri Bibbs",
    "Team": "SF",
    "ATT": 9.8,
    "YDS": 42.2,
    "TDS": 0.1,
    "REC": 1.9,
    "REC YDS": 20.3,
    "REC TDS": 0.1,
    "FL": 0.2,
    "FPTS": 7.1
  },
  {
    "Player": "Josh Ferguson",
    "Team": "IND",
    "ATT": 9.3,
    "YDS": 28.5,
    "TDS": 0.1,
    "REC": 5.6,
    "REC YDS": 40.5,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 6.9
  },
  {
    "Player": "John Crockett",
    "Team": "OAK",
    "ATT": 10,
    "YDS": 40,
    "TDS": 0.2,
    "REC": 2,
    "REC YDS": 12,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 6.8
  },
  {
    "Player": "C.J. Spiller",
    "Team": "KC",
    "ATT": 7.9,
    "YDS": 29,
    "TDS": 0,
    "REC": 4.1,
    "REC YDS": 31.1,
    "REC TDS": 0.2,
    "FL": 0.2,
    "FPTS": 6.7
  },
  {
    "Player": "Khalfani Muhammad",
    "Team": "TEN",
    "ATT": 10,
    "YDS": 36.3,
    "TDS": 0.2,
    "REC": 1.9,
    "REC YDS": 14.4,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 6.7
  },
  {
    "Player": "Derek Watt",
    "Team": "LAC",
    "ATT": 3.9,
    "YDS": 15.9,
    "TDS": 0.2,
    "REC": 3.5,
    "REC YDS": 38.6,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 6.4
  },
  {
    "Player": "Jalston Fowler",
    "Team": "TEN",
    "ATT": 6,
    "YDS": 20.1,
    "TDS": 0.2,
    "REC": 2.7,
    "REC YDS": 26.7,
    "REC TDS": 0.1,
    "FL": 0,
    "FPTS": 6.3
  },
  {
    "Player": "Bobby Rainey",
    "Team": "BAL",
    "ATT": 9.1,
    "YDS": 36.8,
    "TDS": 0.2,
    "REC": 2.5,
    "REC YDS": 15,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 6
  },
  {
    "Player": "Akeem Hunt",
    "Team": "HOU",
    "ATT": 7.7,
    "YDS": 36.4,
    "TDS": 0.2,
    "REC": 2.1,
    "REC YDS": 14,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 5.7
  },
  {
    "Player": "Jonathan Grimes",
    "Team": "JAC",
    "ATT": 5.5,
    "YDS": 28,
    "TDS": 0.1,
    "REC": 3.5,
    "REC YDS": 26,
    "REC TDS": 0.1,
    "FL": 0.2,
    "FPTS": 5.6
  },
  {
    "Player": "Knile Davis",
    "Team": "PIT",
    "ATT": 9.4,
    "YDS": 31,
    "TDS": 0,
    "REC": 3.5,
    "REC YDS": 22.9,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 5.4
  },
  {
    "Player": "T.J. Logan",
    "Team": "ARI",
    "ATT": 8,
    "YDS": 29.5,
    "TDS": 0.2,
    "REC": 1.5,
    "REC YDS": 11.5,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 5.1
  },
  {
    "Player": "Raheem Mostert",
    "Team": "SF",
    "ATT": 6.4,
    "YDS": 26.8,
    "TDS": 0.2,
    "REC": 2.1,
    "REC YDS": 14,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 4.9
  },
  {
    "Player": "Juwan Thompson",
    "Team": "DEN",
    "ATT": 8.6,
    "YDS": 31.9,
    "TDS": 0.1,
    "REC": 2.1,
    "REC YDS": 14.3,
    "REC TDS": 0,
    "FL": 0.3,
    "FPTS": 4.8
  },
  {
    "Player": "Brandon Bolden",
    "Team": "NE",
    "ATT": 3.9,
    "YDS": 13.9,
    "TDS": 0,
    "REC": 2.5,
    "REC YDS": 20.1,
    "REC TDS": 0.2,
    "FL": 0.2,
    "FPTS": 4.3
  },
  {
    "Player": "Daniel Lasco",
    "Team": "NO",
    "ATT": 5.5,
    "YDS": 19.7,
    "TDS": 0.1,
    "REC": 2.3,
    "REC YDS": 16,
    "REC TDS": 0.1,
    "FL": 0.1,
    "FPTS": 4.3
  },
  {
    "Player": "Rod Smith",
    "Team": "DAL",
    "ATT": 3.4,
    "YDS": 12,
    "TDS": 0.1,
    "REC": 2.4,
    "REC YDS": 16.5,
    "REC TDS": 0.1,
    "FL": 0,
    "FPTS": 4.1
  },
  {
    "Player": "Troymaine Pope",
    "Team": "IND",
    "ATT": 8,
    "YDS": 27,
    "TDS": 0.1,
    "REC": 1,
    "REC YDS": 9,
    "REC TDS": 0,
    "FL": 0.1,
    "FPTS": 4
  },
  {
    "Player": "Keith Smith",
    "Team": "DAL",
    "ATT": 4.2,
    "YDS": 16.1,
    "TDS": 0.2,
    "REC": 2.2,
    "REC YDS": 14.2,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 3.9
  },
  {
    "Player": "James Develin",
    "Team": "NE",
    "ATT": 3.2,
    "YDS": 10.2,
    "TDS": 0.1,
    "REC": 2.9,
    "REC YDS": 22.5,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 3.8
  },
  {
    "Player": "Jay Prosch",
    "Team": "HOU",
    "ATT": 2.8,
    "YDS": 9.9,
    "TDS": 0.1,
    "REC": 2.5,
    "REC YDS": 21.7,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 3.5
  },
  {
    "Player": "Dan Vitale",
    "Team": "CLE",
    "ATT": 3.1,
    "YDS": 11.1,
    "TDS": 0.1,
    "REC": 2.5,
    "REC YDS": 16.2,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 3.1
  },
  {
    "Player": "Anthony Sherman",
    "Team": "KC",
    "ATT": 3.1,
    "YDS": 12.8,
    "TDS": 0.1,
    "REC": 1.8,
    "REC YDS": 10.5,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 2.6
  },
  {
    "Player": "Roosevelt Nix",
    "Team": "PIT",
    "ATT": 1.6,
    "YDS": 5.3,
    "TDS": 0,
    "REC": 1.7,
    "REC YDS": 9.8,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 1.7
  },
  {
    "Player": "Marquez Williams",
    "Team": "JAC",
    "ATT": 2,
    "YDS": 7,
    "TDS": 0,
    "REC": 1,
    "REC YDS": 7,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 1.4
  },
  {
    "Player": "Jordan Todman",
    "Team": "NYJ",
    "ATT": 3,
    "YDS": 17,
    "TDS": 0,
    "REC": 0,
    "REC YDS": 0,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 1.3
  },
  {
    "Player": "Marcus Murphy",
    "Team": "NYJ",
    "ATT": 2.5,
    "YDS": 9,
    "TDS": 0.1,
    "REC": 0.5,
    "REC YDS": 4,
    "REC TDS": 0,
    "FL": 0.2,
    "FPTS": 1.2
  },
  {
    "Player": "Taiwan Jones",
    "Team": "BUF",
    "ATT": 1,
    "YDS": 2.5,
    "TDS": 0,
    "REC": 0.5,
    "REC YDS": 7,
    "REC TDS": 0.1,
    "FL": 0.2,
    "FPTS": 1.2
  },
  {
    "Player": "Sam Rogers",
    "Team": "LAR",
    "ATT": 2,
    "YDS": 5,
    "TDS": 0,
    "REC": 1,
    "REC YDS": 6,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 1.1
  },
  {
    "Player": "Michael Burton",
    "Team": "CHI",
    "ATT": 1,
    "YDS": 1,
    "TDS": 0,
    "REC": 1,
    "REC YDS": 8,
    "REC TDS": 0.1,
    "FL": 0.2,
    "FPTS": 1.1
  },
  {
    "Player": "Austin Johnson",
    "Team": "TB",
    "ATT": 8.3,
    "YDS": 33.8,
    "TDS": 0.1,
    "REC": 3.8,
    "REC YDS": 30.4,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Matt Jones",
    "Team": "WAS",
    "ATT": 6.7,
    "YDS": 27.9,
    "TDS": 0,
    "REC": 2,
    "REC YDS": 22.8,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Ronnie Hillman",
    "Team": "DAL",
    "ATT": 17.2,
    "YDS": 63.3,
    "TDS": 0.4,
    "REC": 5.3,
    "REC YDS": 38.9,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Byron Marshall",
    "Team": "PHI",
    "ATT": 8.3,
    "YDS": 32.8,
    "TDS": 0.2,
    "REC": 3.3,
    "REC YDS": 19.4,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Ryan Hewitt",
    "Team": "CIN",
    "ATT": 3.9,
    "YDS": 10.8,
    "TDS": 0.1,
    "REC": 1.7,
    "REC YDS": 12.8,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "George Atkinson",
    "Team": "OAK",
    "ATT": 0,
    "YDS": 0,
    "TDS": 0,
    "REC": 0,
    "REC YDS": 0,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Cedric Peerman",
    "Team": "CIN",
    "ATT": 15.8,
    "YDS": 55.9,
    "TDS": 0.3,
    "REC": 7,
    "REC YDS": 43.5,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Terrell Watson",
    "Team": "PIT",
    "ATT": 8,
    "YDS": 33.9,
    "TDS": 0.2,
    "REC": 3.2,
    "REC YDS": 21.3,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Joe Banyard",
    "Team": "BUF",
    "ATT": 13.6,
    "YDS": 44.3,
    "TDS": 0.2,
    "REC": 6.3,
    "REC YDS": 39.7,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Joe Kerridge",
    "Team": "GB",
    "ATT": 4.4,
    "YDS": 14.7,
    "TDS": 0.1,
    "REC": 2.8,
    "REC YDS": 16.6,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Senorise Perry",
    "Team": "MIA",
    "ATT": 8.4,
    "YDS": 35.7,
    "TDS": 0.3,
    "REC": 5.5,
    "REC YDS": 42.1,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Mike Davis",
    "Team": "SEA",
    "ATT": 1.6,
    "YDS": 4.7,
    "TDS": 0,
    "REC": 9.1,
    "REC YDS": 66.6,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Bernard Pierce",
    "Team": "DEN",
    "ATT": 7.8,
    "YDS": 30.9,
    "TDS": 0.1,
    "REC": 4,
    "REC YDS": 30.6,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "D.J. Foster",
    "Team": "NE",
    "ATT": 12,
    "YDS": 45.9,
    "TDS": 0.2,
    "REC": 2.7,
    "REC YDS": 18.6,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Storm Johnson",
    "Team": "MIA",
    "ATT": 8.4,
    "YDS": 35.7,
    "TDS": 0.3,
    "REC": 5.5,
    "REC YDS": 42.1,
    "REC TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "",
    "Team": "",
    "ATT": "",
    "YDS": "",
    "TDS": "",
    "REC": "",
    "REC YDS": "",
    "REC TDS": "",
    "FL": "",
    "FPTS": ""
  },
  {
    "Player": "",
    "Team": "",
    "ATT": "",
    "YDS": "",
    "TDS": "",
    "REC": "",
    "REC YDS": "",
    "REC TDS": "",
    "FL": "",
    "FPTS": ""
  }
]