wr_stats =
[
  {
    "Player": "Antonio Brown",
    "Team": "PIT",
    "REC": 105.5,
    "YDS": 1475.6,
    "TDS": 10.2,
    "ATT": 0.3,
    "RUSH YDS": 1.9,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 208.1
  },
  {
    "Player": "DeAndre Hopkins",
    "Team": "HOU",
    "REC": 94.5,
    "YDS": 1322.1,
    "TDS": 9.6,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.6,
    "FPTS": 188.8
  },
  {
    "Player": "Julio Jones",
    "Team": "ATL",
    "REC": 93.7,
    "YDS": 1435.7,
    "TDS": 7,
    "ATT": 0.9,
    "RUSH YDS": 8.4,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 185.7
  },
  {
    "Player": "Odell Beckham",
    "Team": "NYG",
    "REC": 97.2,
    "YDS": 1252.3,
    "TDS": 8.3,
    "ATT": 2.3,
    "RUSH YDS": 16.4,
    "RUSH TDS": 0,
    "FL": 0.6,
    "FPTS": 175.4
  },
  {
    "Player": "Michael Thomas",
    "Team": "NO",
    "REC": 99.3,
    "YDS": 1249,
    "TDS": 7.6,
    "ATT": 0.2,
    "RUSH YDS": 0.8,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 169.8
  },
  {
    "Player": "Keenan Allen",
    "Team": "LAC",
    "REC": 95.9,
    "YDS": 1271.2,
    "TDS": 7.1,
    "ATT": 1.2,
    "RUSH YDS": 5.6,
    "RUSH TDS": 0,
    "FL": 0.5,
    "FPTS": 169.6
  },
  {
    "Player": "Davante Adams",
    "Team": "GB",
    "REC": 85.4,
    "YDS": 1075.7,
    "TDS": 9.1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 161.2
  },
  {
    "Player": "A.J. Green",
    "Team": "CIN",
    "REC": 85.4,
    "YDS": 1180.4,
    "TDS": 7.4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 1.2,
    "FPTS": 159.9
  },
  {
    "Player": "Mike Evans",
    "Team": "TB",
    "REC": 81.4,
    "YDS": 1128.6,
    "TDS": 6.9,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 153.6
  },
  {
    "Player": "Tyreek Hill",
    "Team": "KC",
    "REC": 76.1,
    "YDS": 1015.4,
    "TDS": 6.4,
    "ATT": 16.4,
    "RUSH YDS": 100.2,
    "RUSH TDS": 0.8,
    "FL": 0.4,
    "FPTS": 153.5
  },
  {
    "Player": "T.Y. Hilton",
    "Team": "IND",
    "REC": 72.3,
    "YDS": 1083.5,
    "TDS": 6.4,
    "ATT": 0,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.7,
    "FPTS": 145.2
  },
  {
    "Player": "Stefon Diggs",
    "Team": "MIN",
    "REC": 78.9,
    "YDS": 1018.3,
    "TDS": 6.7,
    "ATT": 5.8,
    "RUSH YDS": 26.1,
    "RUSH TDS": 0.1,
    "FL": 0.4,
    "FPTS": 144.2
  },
  {
    "Player": "Doug Baldwin",
    "Team": "SEA",
    "REC": 77.1,
    "YDS": 1001.7,
    "TDS": 7,
    "ATT": 2,
    "RUSH YDS": 5.6,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 142.3
  },
  {
    "Player": "Amari Cooper",
    "Team": "OAK",
    "REC": 78.1,
    "YDS": 1032.6,
    "TDS": 6.5,
    "ATT": 0.9,
    "RUSH YDS": 6,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 142.3
  },
  {
    "Player": "Adam Thielen",
    "Team": "MIN",
    "REC": 80.8,
    "YDS": 1068.7,
    "TDS": 5.5,
    "ATT": 1.2,
    "RUSH YDS": 7.4,
    "RUSH TDS": 0,
    "FL": 1.2,
    "FPTS": 138.5
  },
  {
    "Player": "JuJu Smith-Schuster",
    "Team": "PIT",
    "REC": 66.2,
    "YDS": 926.8,
    "TDS": 7.1,
    "ATT": 0.2,
    "RUSH YDS": 2,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 134.8
  },
  {
    "Player": "Marvin Jones",
    "Team": "DET",
    "REC": 61.2,
    "YDS": 938.3,
    "TDS": 6.6,
    "ATT": 0,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 132.9
  },
  {
    "Player": "Larry Fitzgerald",
    "Team": "ARI",
    "REC": 96.3,
    "YDS": 1009.7,
    "TDS": 5.5,
    "ATT": 0,
    "RUSH YDS": 0.1,
    "RUSH TDS": 0,
    "FL": 0.8,
    "FPTS": 132.4
  },
  {
    "Player": "Demaryius Thomas",
    "Team": "DEN",
    "REC": 82.5,
    "YDS": 982.7,
    "TDS": 5.9,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.8,
    "FPTS": 132.2
  },
  {
    "Player": "Allen Robinson",
    "Team": "CHI",
    "REC": 69.3,
    "YDS": 952.3,
    "TDS": 5.8,
    "ATT": 0.2,
    "RUSH YDS": 0.8,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 129.7
  },
  {
    "Player": "Brandin Cooks",
    "Team": "LAR",
    "REC": 61.1,
    "YDS": 889.1,
    "TDS": 6,
    "ATT": 6.9,
    "RUSH YDS": 36.4,
    "RUSH TDS": 0.3,
    "FL": 0.4,
    "FPTS": 129.2
  },
  {
    "Player": "Golden Tate",
    "Team": "DET",
    "REC": 89.6,
    "YDS": 982.9,
    "TDS": 4.9,
    "ATT": 5.1,
    "RUSH YDS": 20.2,
    "RUSH TDS": 0,
    "FL": 0.8,
    "FPTS": 128.6
  },
  {
    "Player": "Josh Gordon",
    "Team": "NE",
    "REC": 62.6,
    "YDS": 952.6,
    "TDS": 5.4,
    "ATT": 0.6,
    "RUSH YDS": 3,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 127.1
  },
  {
    "Player": "Marquise Goodwin",
    "Team": "SF",
    "REC": 59.7,
    "YDS": 918.8,
    "TDS": 5.2,
    "ATT": 3.4,
    "RUSH YDS": 25.8,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 125.1
  },
  {
    "Player": "Chris Hogan",
    "Team": "NE",
    "REC": 60,
    "YDS": 839.1,
    "TDS": 6.4,
    "ATT": 2.8,
    "RUSH YDS": 14.9,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 123.3
  },
  {
    "Player": "Jarvis Landry",
    "Team": "CLE",
    "REC": 87.5,
    "YDS": 938.1,
    "TDS": 5.3,
    "ATT": 1.1,
    "RUSH YDS": 4.4,
    "RUSH TDS": 0,
    "FL": 1.5,
    "FPTS": 123
  },
  {
    "Player": "Michael Crabtree",
    "Team": "BAL",
    "REC": 74,
    "YDS": 832.9,
    "TDS": 6,
    "ATT": 0,
    "RUSH YDS": 0.1,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 118.6
  },
  {
    "Player": "Devin Funchess",
    "Team": "CAR",
    "REC": 57.5,
    "YDS": 822.1,
    "TDS": 6,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 117.6
  },
  {
    "Player": "Robby Anderson",
    "Team": "NYJ",
    "REC": 62.6,
    "YDS": 852.6,
    "TDS": 5.2,
    "ATT": 2.8,
    "RUSH YDS": 16.1,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 117.6
  },
  {
    "Player": "Robert Woods",
    "Team": "LAR",
    "REC": 62.7,
    "YDS": 848.8,
    "TDS": 5.1,
    "ATT": 2,
    "RUSH YDS": 10.8,
    "RUSH TDS": 0,
    "FL": 0.7,
    "FPTS": 115.4
  },
  {
    "Player": "Cooper Kupp",
    "Team": "LAR",
    "REC": 62.7,
    "YDS": 830.6,
    "TDS": 5.4,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.7,
    "FPTS": 113.7
  },
  {
    "Player": "Sammy Watkins",
    "Team": "KC",
    "REC": 56.6,
    "YDS": 790.2,
    "TDS": 5.5,
    "ATT": 0.3,
    "RUSH YDS": 1.1,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 111.7
  },
  {
    "Player": "Emmanuel Sanders",
    "Team": "DEN",
    "REC": 68.1,
    "YDS": 842.8,
    "TDS": 4.5,
    "ATT": 0.1,
    "RUSH YDS": 3.5,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 111
  },
  {
    "Player": "Pierre Garcon",
    "Team": "SF",
    "REC": 68.1,
    "YDS": 866.1,
    "TDS": 4.1,
    "ATT": 0.1,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 110.8
  },
  {
    "Player": "Jamison Crowder",
    "Team": "WAS",
    "REC": 71.2,
    "YDS": 838.9,
    "TDS": 4.5,
    "ATT": 4.3,
    "RUSH YDS": 19.6,
    "RUSH TDS": 0.1,
    "FL": 1.5,
    "FPTS": 110.3
  },
  {
    "Player": "Corey Davis",
    "Team": "TEN",
    "REC": 67.9,
    "YDS": 811.5,
    "TDS": 5,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 1,
    "FPTS": 108.9
  },
  {
    "Player": "Kenny Stills",
    "Team": "MIA",
    "REC": 56.5,
    "YDS": 802.8,
    "TDS": 4.8,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 1,
    "FPTS": 106.9
  },
  {
    "Player": "Nelson Agholor",
    "Team": "PHI",
    "REC": 60.4,
    "YDS": 726.5,
    "TDS": 5.2,
    "ATT": 3.2,
    "RUSH YDS": 18.6,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 105.1
  },
  {
    "Player": "Alshon Jeffery",
    "Team": "PHI",
    "REC": 50,
    "YDS": 713,
    "TDS": 5.7,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 105
  },
  {
    "Player": "Will Fuller",
    "Team": "HOU",
    "REC": 51.5,
    "YDS": 722.7,
    "TDS": 5.4,
    "ATT": 2.3,
    "RUSH YDS": 10,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 104.9
  },
  {
    "Player": "Keelan Cole",
    "Team": "JAC",
    "REC": 51.3,
    "YDS": 764.8,
    "TDS": 4.7,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.7,
    "FPTS": 103.1
  },
  {
    "Player": "Sterling Shepard",
    "Team": "NYG",
    "REC": 63.7,
    "YDS": 761.7,
    "TDS": 4.3,
    "ATT": 2.7,
    "RUSH YDS": 10.8,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 102.4
  },
  {
    "Player": "Kelvin Benjamin",
    "Team": "BUF",
    "REC": 55.3,
    "YDS": 759.1,
    "TDS": 4.4,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 101.9
  },
  {
    "Player": "Jordy Nelson",
    "Team": "OAK",
    "REC": 66.7,
    "YDS": 713.9,
    "TDS": 5.1,
    "ATT": 0.7,
    "RUSH YDS": 3.8,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 101.5
  },
  {
    "Player": "Randall Cobb",
    "Team": "GB",
    "REC": 65.8,
    "YDS": 687,
    "TDS": 4.9,
    "ATT": 6.8,
    "RUSH YDS": 33.2,
    "RUSH TDS": 0.1,
    "FL": 0.4,
    "FPTS": 101.3
  },
  {
    "Player": "Kenny Golladay",
    "Team": "DET",
    "REC": 46.8,
    "YDS": 715.6,
    "TDS": 4.5,
    "ATT": 0.9,
    "RUSH YDS": 5.4,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 98.4
  },
  {
    "Player": "Julian Edelman",
    "Team": "NE",
    "REC": 60.9,
    "YDS": 701.9,
    "TDS": 4.1,
    "ATT": 4.3,
    "RUSH YDS": 22.2,
    "RUSH TDS": 0,
    "FL": 0.7,
    "FPTS": 95.7
  },
  {
    "Player": "DeSean Jackson",
    "Team": "TB",
    "REC": 48.4,
    "YDS": 701.4,
    "TDS": 3.7,
    "ATT": 2.9,
    "RUSH YDS": 21.8,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 94.3
  },
  {
    "Player": "Ted Ginn",
    "Team": "NO",
    "REC": 45.1,
    "YDS": 666.9,
    "TDS": 4,
    "ATT": 5.7,
    "RUSH YDS": 35.2,
    "RUSH TDS": 0.1,
    "FL": 0.4,
    "FPTS": 93.8
  },
  {
    "Player": "Allen Hurns",
    "Team": "DAL",
    "REC": 53.9,
    "YDS": 696,
    "TDS": 4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 92.9
  },
  {
    "Player": "Mohamed Sanu",
    "Team": "ATL",
    "REC": 59.6,
    "YDS": 672.7,
    "TDS": 4.2,
    "ATT": 2.3,
    "RUSH YDS": 11.1,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 92.8
  },
  {
    "Player": "Tyrell Williams",
    "Team": "LAC",
    "REC": 43.3,
    "YDS": 674.4,
    "TDS": 4.3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.5,
    "FPTS": 92.3
  },
  {
    "Player": "Josh Doctson",
    "Team": "WAS",
    "REC": 45.2,
    "YDS": 634.2,
    "TDS": 4.7,
    "ATT": 0.7,
    "RUSH YDS": -0.8,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 90.8
  },
  {
    "Player": "Devante Parker",
    "Team": "MIA",
    "REC": 54.6,
    "YDS": 691.6,
    "TDS": 3.7,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 90.5
  },
  {
    "Player": "Tyler Lockett",
    "Team": "SEA",
    "REC": 47.3,
    "YDS": 604.8,
    "TDS": 3.5,
    "ATT": 8.2,
    "RUSH YDS": 57.3,
    "RUSH TDS": 0.4,
    "FL": 0.4,
    "FPTS": 89
  },
  {
    "Player": "Dede Westbrook",
    "Team": "JAC",
    "REC": 47.7,
    "YDS": 629.5,
    "TDS": 3.6,
    "ATT": 0,
    "RUSH YDS": 0.7,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 84.4
  },
  {
    "Player": "John Ross",
    "Team": "CIN",
    "REC": 46.5,
    "YDS": 604.7,
    "TDS": 3.7,
    "ATT": 2.9,
    "RUSH YDS": 19.5,
    "RUSH TDS": 0,
    "FL": 0.6,
    "FPTS": 83.3
  },
  {
    "Player": "Danny Amendola",
    "Team": "MIA",
    "REC": 54.7,
    "YDS": 639.1,
    "TDS": 3.3,
    "ATT": 0.6,
    "RUSH YDS": 2.9,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 83.3
  },
  {
    "Player": "John Brown",
    "Team": "BAL",
    "REC": 45.6,
    "YDS": 594,
    "TDS": 3.5,
    "ATT": 1.4,
    "RUSH YDS": 10.3,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 81
  },
  {
    "Player": "Paul Richardson",
    "Team": "WAS",
    "REC": 44.4,
    "YDS": 619,
    "TDS": 3.2,
    "ATT": 0.1,
    "RUSH YDS": 2.1,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 80.7
  },
  {
    "Player": "Cameron Meredith",
    "Team": "NO",
    "REC": 45.1,
    "YDS": 597.8,
    "TDS": 3.8,
    "ATT": 0.2,
    "RUSH YDS": 1.2,
    "RUSH TDS": 0,
    "FL": 1.1,
    "FPTS": 80.5
  },
  {
    "Player": "Mike Wallace",
    "Team": "PHI",
    "REC": 37.8,
    "YDS": 573.5,
    "TDS": 3.8,
    "ATT": 0.8,
    "RUSH YDS": 5,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 79.9
  },
  {
    "Player": "D.J. Moore",
    "Team": "CAR",
    "REC": 42.4,
    "YDS": 577.9,
    "TDS": 3.6,
    "ATT": 0.7,
    "RUSH YDS": 5.8,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 79.2
  },
  {
    "Player": "Quincy Enunwa",
    "Team": "NYJ",
    "REC": 42.7,
    "YDS": 583.1,
    "TDS": 3.4,
    "ATT": 0.3,
    "RUSH YDS": 2.2,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 78.5
  },
  {
    "Player": "Calvin Ridley",
    "Team": "ATL",
    "REC": 45.3,
    "YDS": 550.2,
    "TDS": 3.6,
    "ATT": 0.6,
    "RUSH YDS": 5,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 76.3
  },
  {
    "Player": "Donte Moncrief",
    "Team": "JAC",
    "REC": 41.1,
    "YDS": 543.3,
    "TDS": 3.7,
    "ATT": 0.1,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 76.1
  },
  {
    "Player": "Chris Godwin",
    "Team": "TB",
    "REC": 43.3,
    "YDS": 590,
    "TDS": 2.8,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 75.3
  },
  {
    "Player": "Ryan Grant",
    "Team": "IND",
    "REC": 39.8,
    "YDS": 516.7,
    "TDS": 3.6,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 72.5
  },
  {
    "Player": "Jermaine Kearse",
    "Team": "NYJ",
    "REC": 42.2,
    "YDS": 546,
    "TDS": 3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 71.9
  },
  {
    "Player": "Michael Gallup",
    "Team": "DAL",
    "REC": 41.8,
    "YDS": 506.8,
    "TDS": 3.4,
    "ATT": 0.4,
    "RUSH YDS": 3.8,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 70.5
  },
  {
    "Player": "Anthony Miller",
    "Team": "CHI",
    "REC": 43.3,
    "YDS": 524.4,
    "TDS": 3,
    "ATT": 0.4,
    "RUSH YDS": 2.3,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 70.1
  },
  {
    "Player": "James Washington",
    "Team": "PIT",
    "REC": 34.8,
    "YDS": 502.9,
    "TDS": 3.4,
    "ATT": 0.4,
    "RUSH YDS": 2.8,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 70.1
  },
  {
    "Player": "Courtland Sutton",
    "Team": "DEN",
    "REC": 42.9,
    "YDS": 519.9,
    "TDS": 3,
    "ATT": 0.4,
    "RUSH YDS": 2.5,
    "RUSH TDS": 0,
    "FL": 0.5,
    "FPTS": 69.4
  },
  {
    "Player": "Christian Kirk",
    "Team": "ARI",
    "REC": 44.9,
    "YDS": 527,
    "TDS": 2.8,
    "ATT": 0.6,
    "RUSH YDS": 3.5,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 69.3
  },
  {
    "Player": "Travis Benjamin",
    "Team": "LAC",
    "REC": 30.7,
    "YDS": 481.3,
    "TDS": 2.9,
    "ATT": 6.2,
    "RUSH YDS": 42.5,
    "RUSH TDS": 0.1,
    "FL": 0.6,
    "FPTS": 69
  },
  {
    "Player": "Mike Williams",
    "Team": "LAC",
    "REC": 39.9,
    "YDS": 478.2,
    "TDS": 3.6,
    "ATT": 0,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 68.9
  },
  {
    "Player": "Geronimo Allison",
    "Team": "GB",
    "REC": 39.9,
    "YDS": 486.9,
    "TDS": 3.3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.8,
    "FPTS": 66.7
  },
  {
    "Player": "Terrance Williams",
    "Team": "DAL",
    "REC": 40.7,
    "YDS": 504.4,
    "TDS": 2.7,
    "ATT": 1.4,
    "RUSH YDS": 6.8,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 66.5
  },
  {
    "Player": "Taywan Taylor",
    "Team": "TEN",
    "REC": 38.2,
    "YDS": 457.2,
    "TDS": 2.5,
    "ATT": 4.4,
    "RUSH YDS": 24.4,
    "RUSH TDS": 0.1,
    "FL": 0.2,
    "FPTS": 63.2
  },
  {
    "Player": "Albert Wilson",
    "Team": "MIA",
    "REC": 39.7,
    "YDS": 462.5,
    "TDS": 2.4,
    "ATT": 1.9,
    "RUSH YDS": 10.4,
    "RUSH TDS": 0.1,
    "FL": 0.2,
    "FPTS": 61.9
  },
  {
    "Player": "Cole Beasley",
    "Team": "DAL",
    "REC": 42.8,
    "YDS": 434.8,
    "TDS": 2.7,
    "ATT": 0.1,
    "RUSH YDS": 0.6,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 59.4
  },
  {
    "Player": "Zay Jones",
    "Team": "BUF",
    "REC": 34.1,
    "YDS": 435.2,
    "TDS": 2.5,
    "ATT": 0,
    "RUSH YDS": 1.6,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 58.2
  },
  {
    "Player": "J.J. Nelson",
    "Team": "ARI",
    "REC": 28.2,
    "YDS": 428.4,
    "TDS": 2.2,
    "ATT": 2.5,
    "RUSH YDS": 22.7,
    "RUSH TDS": 0.1,
    "FL": 0.7,
    "FPTS": 57.3
  },
  {
    "Player": "Chester Rogers",
    "Team": "IND",
    "REC": 33.4,
    "YDS": 429.8,
    "TDS": 2.3,
    "ATT": 2,
    "RUSH YDS": 8.1,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 57.3
  },
  {
    "Player": "Brandon Marshall",
    "Team": "SEA",
    "REC": 33.9,
    "YDS": 406.3,
    "TDS": 2.7,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 56.3
  },
  {
    "Player": "Phillip Dorsett",
    "Team": "NE",
    "REC": 29,
    "YDS": 418.6,
    "TDS": 2.3,
    "ATT": 0.7,
    "RUSH YDS": 3.4,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 55.8
  },
  {
    "Player": "Trent Taylor",
    "Team": "SF",
    "REC": 37.3,
    "YDS": 427.7,
    "TDS": 2.3,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.8,
    "FPTS": 55.2
  },
  {
    "Player": "Terrelle Pryor",
    "Team": "NYJ",
    "REC": 33.1,
    "YDS": 406.9,
    "TDS": 2.1,
    "ATT": 1.4,
    "RUSH YDS": 5,
    "RUSH TDS": 0.1,
    "FL": 0.3,
    "FPTS": 53.6
  },
  {
    "Player": "Seth Roberts",
    "Team": "OAK",
    "REC": 38.4,
    "YDS": 409,
    "TDS": 2.2,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.6,
    "FPTS": 53
  },
  {
    "Player": "Willie Snead",
    "Team": "BAL",
    "REC": 39.1,
    "YDS": 417.9,
    "TDS": 2,
    "ATT": 0,
    "RUSH YDS": 0.8,
    "RUSH TDS": 0,
    "FL": 0.5,
    "FPTS": 52.8
  },
  {
    "Player": "Laquon Treadwell",
    "Team": "MIN",
    "REC": 34,
    "YDS": 380.5,
    "TDS": 2.3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 51.1
  },
  {
    "Player": "Tyler Boyd",
    "Team": "CIN",
    "REC": 30.6,
    "YDS": 385.4,
    "TDS": 2.1,
    "ATT": 0.5,
    "RUSH YDS": 5.2,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 51.1
  },
  {
    "Player": "Taylor Gabriel",
    "Team": "CHI",
    "REC": 29.5,
    "YDS": 374.8,
    "TDS": 2,
    "ATT": 2.8,
    "RUSH YDS": 15.9,
    "RUSH TDS": 0.1,
    "FL": 0.2,
    "FPTS": 50.8
  },
  {
    "Player": "Adam Humphries",
    "Team": "TB",
    "REC": 35.9,
    "YDS": 401,
    "TDS": 1.8,
    "ATT": 1.1,
    "RUSH YDS": 5.8,
    "RUSH TDS": 0,
    "FL": 0.5,
    "FPTS": 50.5
  },
  {
    "Player": "Chad Williams",
    "Team": "ARI",
    "REC": 29.7,
    "YDS": 373.9,
    "TDS": 1.9,
    "ATT": 2.2,
    "RUSH YDS": 19,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 50.3
  },
  {
    "Player": "Antonio Callaway",
    "Team": "CLE",
    "REC": 30.9,
    "YDS": 371.5,
    "TDS": 2.1,
    "ATT": 0.4,
    "RUSH YDS": 2.5,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 49.2
  },
  {
    "Player": "Tre'Quan Smith",
    "Team": "NO",
    "REC": 27.8,
    "YDS": 355.6,
    "TDS": 2.3,
    "ATT": 0.4,
    "RUSH YDS": 2.7,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 48.8
  },
  {
    "Player": "Brandon LaFell",
    "Team": "OAK",
    "REC": 26,
    "YDS": 369.3,
    "TDS": 2,
    "ATT": 0,
    "RUSH YDS": 0.1,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 48.7
  },
  {
    "Player": "Cordarrelle Patterson",
    "Team": "NE",
    "REC": 24,
    "YDS": 266.2,
    "TDS": 1.5,
    "ATT": 11.8,
    "RUSH YDS": 87.3,
    "RUSH TDS": 0.5,
    "FL": 0.3,
    "FPTS": 46.9
  },
  {
    "Player": "Dante Pettis",
    "Team": "SF",
    "REC": 26.8,
    "YDS": 341,
    "TDS": 1.9,
    "ATT": 0.5,
    "RUSH YDS": 3.4,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 45.3
  },
  {
    "Player": "Jaron Brown",
    "Team": "SEA",
    "REC": 22.7,
    "YDS": 312.3,
    "TDS": 2.4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 45.2
  },
  {
    "Player": "Cody Latimer",
    "Team": "NYG",
    "REC": 26.7,
    "YDS": 334.3,
    "TDS": 1.9,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 44.6
  },
  {
    "Player": "Torrey Smith",
    "Team": "CAR",
    "REC": 23.6,
    "YDS": 320.2,
    "TDS": 1.9,
    "ATT": 0.5,
    "RUSH YDS": 0.8,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 42.9
  },
  {
    "Player": "Bruce Ellington",
    "Team": "HOU",
    "REC": 24.3,
    "YDS": 318,
    "TDS": 1.8,
    "ATT": 1.9,
    "RUSH YDS": 10,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 42.7
  },
  {
    "Player": "D.J. Chark",
    "Team": "JAC",
    "REC": 21,
    "YDS": 279.2,
    "TDS": 1.8,
    "ATT": 0.4,
    "RUSH YDS": 3,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 38.5
  },
  {
    "Player": "Chris Conley",
    "Team": "KC",
    "REC": 21.5,
    "YDS": 299.4,
    "TDS": 1.5,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 38.4
  },
  {
    "Player": "TJ Jones",
    "Team": "DET",
    "REC": 21.4,
    "YDS": 281.8,
    "TDS": 1.5,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 36.8
  },
  {
    "Player": "Keke Coutee",
    "Team": "HOU",
    "REC": 21.1,
    "YDS": 255.8,
    "TDS": 1.6,
    "ATT": 0.5,
    "RUSH YDS": 3.2,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 34.8
  },
  {
    "Player": "Curtis Samuel",
    "Team": "CAR",
    "REC": 20.2,
    "YDS": 230.5,
    "TDS": 1.2,
    "ATT": 5,
    "RUSH YDS": 43.3,
    "RUSH TDS": 0.1,
    "FL": 0.2,
    "FPTS": 34.4
  },
  {
    "Player": "Kevin White",
    "Team": "CHI",
    "REC": 18.6,
    "YDS": 279.3,
    "TDS": 1.1,
    "ATT": 0.6,
    "RUSH YDS": 3.4,
    "RUSH TDS": 0,
    "FL": 0.5,
    "FPTS": 34.1
  },
  {
    "Player": "Tavon Austin",
    "Team": "DAL",
    "REC": 17.2,
    "YDS": 144.2,
    "TDS": 0.4,
    "ATT": 20.8,
    "RUSH YDS": 124.2,
    "RUSH TDS": 0.7,
    "FL": 0.4,
    "FPTS": 32.7
  },
  {
    "Player": "Brandon Zylstra",
    "Team": "MIN",
    "REC": 0,
    "YDS": 224.9,
    "TDS": 1.5,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 30.9
  },
  {
    "Player": "Seth DeValve",
    "Team": "CLE",
    "REC": 0,
    "YDS": 227.2,
    "TDS": 1.3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 30.2
  },
  {
    "Player": "Justin Hardy",
    "Team": "ATL",
    "REC": 17.3,
    "YDS": 203.8,
    "TDS": 1.4,
    "ATT": 0.1,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 28.6
  },
  {
    "Player": "Mack Hollins",
    "Team": "PHI",
    "REC": 16.2,
    "YDS": 207.5,
    "TDS": 1.3,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 28.1
  },
  {
    "Player": "Trent Sherfield",
    "Team": "ARI",
    "REC": 0,
    "YDS": 205.5,
    "TDS": 1.4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 28.1
  },
  {
    "Player": "Tim Patrick",
    "Team": "DEN",
    "REC": 0,
    "YDS": 202.5,
    "TDS": 1.3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 27.6
  },
  {
    "Player": "Chris Moore",
    "Team": "BAL",
    "REC": 16.1,
    "YDS": 194.8,
    "TDS": 1.3,
    "ATT": 1.9,
    "RUSH YDS": 5.4,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 27.2
  },
  {
    "Player": "Andre Holmes",
    "Team": "BUF",
    "REC": 16.5,
    "YDS": 182.6,
    "TDS": 1.3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 25.5
  },
  {
    "Player": "Tajae Sharpe",
    "Team": "TEN",
    "REC": 11.7,
    "YDS": 193.2,
    "TDS": 1.1,
    "ATT": 0,
    "RUSH YDS": 0.1,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 25.3
  },
  {
    "Player": "DaeSean Hamilton",
    "Team": "DEN",
    "REC": 14.4,
    "YDS": 189,
    "TDS": 1.1,
    "ATT": 0.5,
    "RUSH YDS": 3.2,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 25.2
  },
  {
    "Player": "Martavis Bryant",
    "Team": "OAK",
    "REC": 12,
    "YDS": 166,
    "TDS": 1.2,
    "ATT": 0,
    "RUSH YDS": 10,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 24.8
  },
  {
    "Player": "Hunter Sharp",
    "Team": "BUF",
    "REC": 14,
    "YDS": 152.1,
    "TDS": 1.4,
    "ATT": 0.5,
    "RUSH YDS": 4.4,
    "RUSH TDS": 0,
    "FL": 0.6,
    "FPTS": 22.7
  },
  {
    "Player": "Jakeem Grant",
    "Team": "MIA",
    "REC": 12.3,
    "YDS": 173.2,
    "TDS": 1,
    "ATT": 2,
    "RUSH YDS": 8.4,
    "RUSH TDS": 0,
    "FL": 0.9,
    "FPTS": 22.5
  },
  {
    "Player": "J'Mon Moore",
    "Team": "GB",
    "REC": 12.7,
    "YDS": 161.6,
    "TDS": 1.1,
    "ATT": 0.4,
    "RUSH YDS": 2.3,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 22.3
  },
  {
    "Player": "Rashard Higgins",
    "Team": "CLE",
    "REC": 11.4,
    "YDS": 164.5,
    "TDS": 1.1,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 22.3
  },
  {
    "Player": "Robert Foster",
    "Team": "BUF",
    "REC": 0,
    "YDS": 163,
    "TDS": 1.1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 22.2
  },
  {
    "Player": "Josh Reynolds",
    "Team": "LAR",
    "REC": 13.1,
    "YDS": 159.1,
    "TDS": 1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 21.5
  },
  {
    "Player": "David Moore",
    "Team": "SEA",
    "REC": 12.5,
    "YDS": 153.9,
    "TDS": 0.9,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 20.7
  },
  {
    "Player": "Deonte Thompson",
    "Team": "DAL",
    "REC": 14.8,
    "YDS": 159.6,
    "TDS": 0.7,
    "ATT": 0.2,
    "RUSH YDS": 1.4,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 20.4
  },
  {
    "Player": "Demarcus Robinson",
    "Team": "KC",
    "REC": 13.7,
    "YDS": 156.7,
    "TDS": 0.8,
    "ATT": 0,
    "RUSH YDS": 0.1,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 20.3
  },
  {
    "Player": "Eli Rogers",
    "Team": "PIT",
    "REC": 13.4,
    "YDS": 148.9,
    "TDS": 0.9,
    "ATT": 0,
    "RUSH YDS": 0.6,
    "RUSH TDS": 0,
    "FL": 1.2,
    "FPTS": 18.1
  },
  {
    "Player": "Sammie Coates",
    "Team": "HOU",
    "REC": 11.5,
    "YDS": 138.7,
    "TDS": 0.7,
    "ATT": 1.5,
    "RUSH YDS": 2.9,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 17.8
  },
  {
    "Player": "Johnny Holton",
    "Team": "OAK",
    "REC": 11.7,
    "YDS": 153.7,
    "TDS": 1.3,
    "ATT": 0.5,
    "RUSH YDS": 3.7,
    "RUSH TDS": 0,
    "FL": 2.9,
    "FPTS": 17.7
  },
  {
    "Player": "Kendrick Bourne",
    "Team": "SF",
    "REC": 7.2,
    "YDS": 143.7,
    "TDS": 0.5,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 16.9
  },
  {
    "Player": "Jordan Lasley",
    "Team": "BAL",
    "REC": 10.3,
    "YDS": 123.8,
    "TDS": 0.7,
    "ATT": 0,
    "RUSH YDS": 0.3,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 16.3
  },
  {
    "Player": "Josh Bellamy",
    "Team": "CHI",
    "REC": 8.9,
    "YDS": 125.3,
    "TDS": 0.6,
    "ATT": 0.5,
    "RUSH YDS": 2.7,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 16.3
  },
  {
    "Player": "Marquez Valdes-Scantling",
    "Team": "GB",
    "REC": 6.5,
    "YDS": 117.2,
    "TDS": 0.8,
    "ATT": 0,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 16.3
  },
  {
    "Player": "Dan Arnold",
    "Team": "NO",
    "REC": 0,
    "YDS": 114.7,
    "TDS": 0.8,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 15.8
  },
  {
    "Player": "Ray-Ray McCloud",
    "Team": "BUF",
    "REC": 9.5,
    "YDS": 120.5,
    "TDS": 0.6,
    "ATT": 0,
    "RUSH YDS": 1,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 15.5
  },
  {
    "Player": "J.D. McKissic",
    "Team": "SEA",
    "REC": 4,
    "YDS": 95.6,
    "TDS": 0.5,
    "ATT": 5,
    "RUSH YDS": 21,
    "RUSH TDS": 0.2,
    "FL": 0.2,
    "FPTS": 15.2
  },
  {
    "Player": "Equanimeous St. Brown",
    "Team": "GB",
    "REC": 6.3,
    "YDS": 112.3,
    "TDS": 0.7,
    "ATT": 0,
    "RUSH YDS": 0.3,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 14.9
  },
  {
    "Player": "Damion Ratley",
    "Team": "CLE",
    "REC": 6,
    "YDS": 109.1,
    "TDS": 0.6,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 14.1
  },
  {
    "Player": "ArDarius Stewart",
    "Team": "NYJ",
    "REC": 8.2,
    "YDS": 101.7,
    "TDS": 0.5,
    "ATT": 1.2,
    "RUSH YDS": 7.2,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 13.7
  },
  {
    "Player": "Zach Pascal",
    "Team": "IND",
    "REC": 7.7,
    "YDS": 95.1,
    "TDS": 0.7,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 13.4
  },
  {
    "Player": "Janarion Grant",
    "Team": "BAL",
    "REC": 0,
    "YDS": 95.9,
    "TDS": 0.7,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 13
  },
  {
    "Player": "Russell Shepard",
    "Team": "NYG",
    "REC": 6.7,
    "YDS": 101.9,
    "TDS": 0.5,
    "ATT": 0.2,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 12.7
  },
  {
    "Player": "Auden Tate",
    "Team": "CIN",
    "REC": 3.5,
    "YDS": 93.9,
    "TDS": 0.6,
    "ATT": 0,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 12.4
  },
  {
    "Player": "Josh Malone",
    "Team": "CIN",
    "REC": 6.5,
    "YDS": 95.3,
    "TDS": 0.5,
    "ATT": 0.7,
    "RUSH YDS": 1.9,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 12.2
  },
  {
    "Player": "Damiere Byrd",
    "Team": "CAR",
    "REC": 5.9,
    "YDS": 87.5,
    "TDS": 0.5,
    "ATT": 0.3,
    "RUSH YDS": 2,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 11.7
  },
  {
    "Player": "Darrius Heyward-Bey",
    "Team": "PIT",
    "REC": 6.8,
    "YDS": 84.8,
    "TDS": 0.4,
    "ATT": 0.7,
    "RUSH YDS": 7.1,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 11.7
  },
  {
    "Player": "Trevor Davis",
    "Team": "GB",
    "REC": 6.3,
    "YDS": 83.2,
    "TDS": 0.5,
    "ATT": 0.7,
    "RUSH YDS": 5.4,
    "RUSH TDS": 0,
    "FL": 0.5,
    "FPTS": 11
  },
  {
    "Player": "Travis Rudolph",
    "Team": "MIA",
    "REC": 8,
    "YDS": 104,
    "TDS": 0.1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 10.8
  },
  {
    "Player": "Trey Quinn",
    "Team": "WAS",
    "REC": 4,
    "YDS": 85.4,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 0.3,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 10.8
  },
  {
    "Player": "Russell Gage",
    "Team": "ATL",
    "REC": 3,
    "YDS": 80.5,
    "TDS": 0.5,
    "ATT": 0,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 10.7
  },
  {
    "Player": "Marcus Johnson",
    "Team": "IND",
    "REC": 5.3,
    "YDS": 79.5,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 10.3
  },
  {
    "Player": "Justin Hunter",
    "Team": "PIT",
    "REC": 4.2,
    "YDS": 53.1,
    "TDS": 0.8,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 9.6
  },
  {
    "Player": "Bennie Fowler",
    "Team": "NYG",
    "REC": 6,
    "YDS": 72,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 9.6
  },
  {
    "Player": "Jarius Wright",
    "Team": "CAR",
    "REC": 5.7,
    "YDS": 69.3,
    "TDS": 0.5,
    "ATT": 0,
    "RUSH YDS": 0.2,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 9.5
  },
  {
    "Player": "Maurice Harris",
    "Team": "WAS",
    "REC": 5.3,
    "YDS": 70.7,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 9.3
  },
  {
    "Player": "Isaiah McKenzie",
    "Team": "DEN",
    "REC": 2,
    "YDS": 76.6,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 2,
    "RUSH TDS": 0,
    "FL": 0.6,
    "FPTS": 9.2
  },
  {
    "Player": "Tommylee Lewis",
    "Team": "NO",
    "REC": 6.3,
    "YDS": 67.2,
    "TDS": 0.5,
    "ATT": 1.1,
    "RUSH YDS": 4.1,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 9
  },
  {
    "Player": "Ryan Switzer",
    "Team": "PIT",
    "REC": 5.9,
    "YDS": 68,
    "TDS": 0.4,
    "ATT": 1.1,
    "RUSH YDS": 2.9,
    "RUSH TDS": 0,
    "FL": 0.5,
    "FPTS": 8.8
  },
  {
    "Player": "Richie James",
    "Team": "SF",
    "REC": 5.5,
    "YDS": 71,
    "TDS": 0.3,
    "ATT": 0,
    "RUSH YDS": 1,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 8.8
  },
  {
    "Player": "Justin Watson",
    "Team": "TB",
    "REC": 4.3,
    "YDS": 67,
    "TDS": 0.3,
    "ATT": 0,
    "RUSH YDS": 1.3,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 8.5
  },
  {
    "Player": "Pharoh Cooper",
    "Team": "LAR",
    "REC": 7.5,
    "YDS": 79.1,
    "TDS": 0.3,
    "ATT": 0.2,
    "RUSH YDS": 2.8,
    "RUSH TDS": 0,
    "FL": 0.7,
    "FPTS": 8.3
  },
  {
    "Player": "Darius Jennings",
    "Team": "TEN",
    "REC": 5.9,
    "YDS": 62.9,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.3,
    "FPTS": 8.1
  },
  {
    "Player": "Alex Erickson",
    "Team": "CIN",
    "REC": 5.8,
    "YDS": 72.8,
    "TDS": 0.2,
    "ATT": 0.7,
    "RUSH YDS": 3.5,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 8.1
  },
  {
    "Player": "Nick Williams",
    "Team": "LAR",
    "REC": 6,
    "YDS": 69,
    "TDS": 0.2,
    "ATT": 0,
    "RUSH YDS": 1,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 8
  },
  {
    "Player": "Amara Darboh",
    "Team": "SEA",
    "REC": 4,
    "YDS": 58.3,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 7.8
  },
  {
    "Player": "Jaleel Scott",
    "Team": "BAL",
    "REC": 5,
    "YDS": 61,
    "TDS": 0.3,
    "ATT": 0,
    "RUSH YDS": 0.5,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.7
  },
  {
    "Player": "Victor Bolden Jr.",
    "Team": "SF",
    "REC": 4.1,
    "YDS": 52.5,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 7.5
  },
  {
    "Player": "Cody Core",
    "Team": "CIN",
    "REC": 6.6,
    "YDS": 69.4,
    "TDS": 0.1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 7.4
  },
  {
    "Player": "Mike Thomas",
    "Team": "LAR",
    "REC": 4.3,
    "YDS": 70.7,
    "TDS": 0.1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.2,
    "FPTS": 7.3
  },
  {
    "Player": "Geremy Davis",
    "Team": "LAC",
    "REC": 4.1,
    "YDS": 52.5,
    "TDS": 0.4,
    "ATT": 0,
    "RUSH YDS": 0.3,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 7.3
  },
  {
    "Player": "Jaydon Mickens",
    "Team": "JAC",
    "REC": 3.7,
    "YDS": 47.1,
    "TDS": 0.6,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.7,
    "FPTS": 7.1
  },
  {
    "Player": "Marvin Hall",
    "Team": "ATL",
    "REC": 3.6,
    "YDS": 55.5,
    "TDS": 0.3,
    "ATT": 0,
    "RUSH YDS": 0.3,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 7.1
  },
  {
    "Player": "Charone Peake",
    "Team": "NYJ",
    "REC": 5.5,
    "YDS": 55.6,
    "TDS": 0.2,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 6.8
  },
  {
    "Player": "Rashad Greene",
    "Team": "JAC",
    "REC": 5.5,
    "YDS": 50.6,
    "TDS": 0.3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 6.5
  },
  {
    "Player": "Javon Wims",
    "Team": "CHI",
    "REC": 4,
    "YDS": 54,
    "TDS": 0.2,
    "ATT": 0,
    "RUSH YDS": 1,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 6.5
  },
  {
    "Player": "Shane Wynn",
    "Team": "NO",
    "REC": 3,
    "YDS": 50,
    "TDS": 0.2,
    "ATT": 1,
    "RUSH YDS": 4,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 6.4
  },
  {
    "Player": "Austin Carr",
    "Team": "NO",
    "REC": 5,
    "YDS": 45.4,
    "TDS": 0.3,
    "ATT": 0,
    "RUSH YDS": 1,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.3
  },
  {
    "Player": "De'Anthony Thomas",
    "Team": "KC",
    "REC": 5.1,
    "YDS": 47.2,
    "TDS": 0.2,
    "ATT": 0.8,
    "RUSH YDS": 3,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.2
  },
  {
    "Player": "Michael Campanaro",
    "Team": "TEN",
    "REC": 4.5,
    "YDS": 53.1,
    "TDS": 0.1,
    "ATT": 0.3,
    "RUSH YDS": 1.5,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 6.1
  },
  {
    "Player": "Shelton Gibson",
    "Team": "PHI",
    "REC": 4.5,
    "YDS": 50.9,
    "TDS": 0.2,
    "ATT": 0,
    "RUSH YDS": 0.3,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 5.8
  },
  {
    "Player": "Andy Jones",
    "Team": "DET",
    "REC": 3.8,
    "YDS": 44.9,
    "TDS": 0.2,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 5.7
  },
  {
    "Player": "Jordan Taylor",
    "Team": "DEN",
    "REC": 4.5,
    "YDS": 49.5,
    "TDS": 0.1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.1,
    "FPTS": 5.5
  },
  {
    "Player": "Matt Slater",
    "Team": "NE",
    "REC": 3.9,
    "YDS": 36.7,
    "TDS": 0.3,
    "ATT": 0.1,
    "RUSH YDS": 0.4,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 5.4
  },
  {
    "Player": "Cedrick Wilson",
    "Team": "DAL",
    "REC": 2,
    "YDS": 32,
    "TDS": 0.2,
    "ATT": 0,
    "RUSH YDS": 1,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4.5
  },
  {
    "Player": "Noah Brown",
    "Team": "DAL",
    "REC": 3.4,
    "YDS": 33.6,
    "TDS": 0.2,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4.4
  },
  {
    "Player": "Dwayne Harris",
    "Team": "OAK",
    "REC": 2.7,
    "YDS": 33.1,
    "TDS": 0.3,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.4,
    "FPTS": 4.4
  },
  {
    "Player": "DeAndre Carter",
    "Team": "PHI",
    "REC": 0,
    "YDS": 29.4,
    "TDS": 0.2,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 4
  },
  {
    "Player": "Andre Roberts",
    "Team": "NYJ",
    "REC": 3,
    "YDS": 27.4,
    "TDS": 0.1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.6,
    "FPTS": 2.2
  },
  {
    "Player": "Kalif Raymond",
    "Team": "NYG",
    "REC": 1.5,
    "YDS": 18.5,
    "TDS": 0.1,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0.6,
    "FPTS": 1.3
  },
  {
    "Player": "Vince Mayle",
    "Team": "LAC",
    "REC": 0,
    "YDS": 0,
    "TDS": 0,
    "ATT": 0,
    "RUSH YDS": 1,
    "RUSH TDS": 0.2,
    "FL": 0.1,
    "FPTS": 1.1
  },
  {
    "Player": "Marcell Ateman",
    "Team": "OAK",
    "REC": 0,
    "YDS": 0,
    "TDS": 0,
    "ATT": 0,
    "RUSH YDS": 8,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0.8
  },
  {
    "Player": "Braxton Miller",
    "Team": "PHI",
    "REC": 0,
    "YDS": 0,
    "TDS": 0,
    "ATT": 0,
    "RUSH YDS": 6,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0.6
  },
  {
    "Player": "Byron Marshall",
    "Team": "WAS",
    "REC": 0,
    "YDS": 0,
    "TDS": 0,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  },
  {
    "Player": "Justin Hardee",
    "Team": "NO",
    "REC": 0,
    "YDS": 0,
    "TDS": 0,
    "ATT": 0,
    "RUSH YDS": 0,
    "RUSH TDS": 0,
    "FL": 0,
    "FPTS": 0
  }
]